import React, { createContext, useContext, useState, useCallback } from 'react';

type Language = 'de' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  de: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'Über uns',
    'nav.sales': 'Vertrieb & Aftersales',
    'nav.applications': 'Anwendungen',
    'nav.products': 'Produkte',
    'nav.integration': 'Systemintegration',
    'nav.news': 'News & Medien',

    // Footer
    'footer.terms': 'AGB',
    'footer.privacy': 'Datenschutz',
    'footer.legal': 'Impressum',
    'footer.dealers': 'Händler',

    // Hero
    'hero.headline': 'Next Level Separation',
    'hero.subheadline': 'Innovative Lösungen zur Fest-Flüssig-Trennung',
    'hero.cta': 'Mehr erfahren',

    // About Section
    'about.title': 'Über uns',
    'about.description': 'Über 15 Jahre fundierte Expertise in der Entwicklung und technischen Realisierung im Maschinen- und Anlagenbau, mit spezialisiertem Fokus auf zukunftsweisende Separations- und Umwelttechnik.',
    'about.link': 'Zur Unternehmensseite',

    // Applications Section
    'applications.title': 'Anwendungen',
    'applications.learnMore': 'Mehr erfahren',
    'applications.agriculture.title': 'Landwirtschaft',
    'applications.agriculture.desc': 'Gülle von Nutztieren, Gärreste aus Biogasanlagen',
    'applications.bedding.title': 'Einstreuerzeugung',
    'applications.bedding.desc': 'Separation zur Einstreu- und Düngerproduktion',
    'applications.biogas.title': 'Biogas',
    'applications.biogas.desc': 'Gärreste aus Biogasanlagen',
    'applications.recycling.title': 'Kunststoff Recycling',
    'applications.recycling.desc': 'Abwasser aus Depackinganlagen und Kunststoffrecyclinganlagen',
    'applications.municipal.title': 'Kommunalwirtschaft',
    'applications.municipal.desc': 'Primär- und Sekundärschlämme aus Kläranlagen',
    'applications.paper.title': 'Papierindustrie',
    'applications.paper.desc': 'Rejekte und Sekundärschlämme',
    'applications.mdf.title': 'Prozessmedien und Abwässer',
    'applications.mdf.desc': 'Produktionsabwässer und Prozessmedien aus industriellen Anlagen',
    'applications.food.title': 'Nebenprodukte und Abwässer',
    'applications.food.desc': 'Schlachthausabwasser, Waschwasser, Brauereiabfälle und industrielle Nebenprodukte',

    // Products Section
    'products.title': 'Produkte',
    'products.viewDetails': 'Zu den Details',
    'products.bg2.name': 'Filterschneckenpresse BGII-800',
    'products.bg2.feature1': 'Bis zu 75m³/h Durchsatz',
    'products.bg2.feature2': 'Bis zu 75% TS-Gehalt',
    'products.bg2.feature3': 'Edelstahlkonstruktion',
    'products.bgi400.name': 'Filterschneckenpresse BGI-400',
    'products.bgi400.feature1': 'Bis zu 20m³/h Durchsatz',
    'products.bgi400.feature2': 'Kompakte Bauweise',
    'products.bgi400.feature3': 'Plug & Play Lösung',

    // Why Separation Section
    'why.title': 'Warum separieren?',
    'why.point1': 'Verringerung von Lagervolumen',
    'why.point2': 'Wiederverwendung der Feststoffe',
    'why.point3': 'Reduktion der Entsorgungskosten',
    'why.point4': 'Wiederverwendung der Flüssigphase als Prozesswasser',
    'why.point5': 'Reduktion der Energiekosten',
    'why.point6': 'Reduktion von Prozesskosten',
    'why.point7': 'Einhaltung von Umweltvorgaben',
    'why.point8': 'Verbesserte Eigenschaften der separierten Phasen',

    // Optimization Section
    'optimization.label': 'Prozessoptimierung',
    'optimization.title': 'Messbar effizienter',
    'optimization.text': 'Wir machen Separationsprozesse messbar effizienter. Durch intelligente Optimierungen reduzieren wir Energieverbrauch, Verschleiß und Betriebskosten – und steigern gleichzeitig die Leistungsfähigkeit bestehender Systeme. Dabei bleibt es nicht bei der Analyse: Wir setzen Verbesserungen gemeinsam mit unseren Kunden konsequent um und schaffen so nachhaltigen Mehrwert.',

    // News Section
    'news.title': 'News & Erfolgsgeschichten',
    'news.readMore': 'Weiterlesen',

    // About Page
    'aboutpage.intro.title': 'Wer sind wir?',
    'aboutpage.vision.title': 'Vision & Mission',
    'aboutpage.vision.label': 'Vision:',
    'aboutpage.vision.text': 'Separationstechnik auf das nächste Level bringen',
    'aboutpage.slogan.label': 'Slogan:',
    'aboutpage.slogan.text': 'Next Level Separation',
    'aboutpage.mission.label': 'Mission:',
    'aboutpage.mission.text': 'Wir machen Separationsprozesse messbar effizienter. Durch intelligente Optimierungen reduzieren wir Energieverbrauch, Verschleiß und Betriebskosten – und steigern gleichzeitig die Leistungsfähigkeit bestehender Systeme. Dabei bleibt es nicht bei der Analyse: Wir setzen Verbesserungen gemeinsam mit unseren Kund:innen konsequent um und schaffen so nachhaltigen Mehrwert.',
    'aboutpage.team.title': 'Unser Team',
    'aboutpage.team.ceo.name': 'Heinz Leitner',
    'aboutpage.team.ceo.role': 'CEO',
    'aboutpage.team.ceo.bio': '>15 Jahre einschlägige Managementerfahrung im internationalen Umwelttechnikmaschinen- und Anlagenbau',
    'aboutpage.team.coo.name': 'Gernot Pauger',
    'aboutpage.team.coo.role': 'COO',
    'aboutpage.team.coo.bio': '>15 Jahre Erfahrung in der Entwicklung und Produktion von Sondermaschinen für Umwelt- und Landtechnik',
    'aboutpage.team.cto.name': 'Thomas Kampl',
    'aboutpage.team.cto.role': 'CTO',
    'aboutpage.team.cto.bio': '>15 Jahre Erfahrung als Anwendungsspezialist im Bereich von Separationstechnik für Fest-Flüssigtrennung',
    'aboutpage.team.cso.name': 'Günther Pirker',
    'aboutpage.team.cso.role': 'CSO',
    'aboutpage.team.cso.bio': '>15 Jahre Branchenerfahrung mit Schwerpunkt Produktion und internationalem Vertrieb von Land- und Umwelttechnikmaschinen',
    'aboutpage.team.description': 'Wir sind ein interdisziplinäres Team aus Ingenieuren, Anwendungsspezialisten und Branchenkennern, das eines verbindet: der Anspruch, technologisch führende Lösungen für die Separation von flüssigen und festen Stoffen zu entwickeln. Unser Ansatz ist systemorientiert und lösungsfokussiert. Wir analysieren etablierte Aufbereitungsprozesse ganzheitlich, entwickeln maßgeschneiderte Maschinen- und Anlagenkonzepte mit deutlich höherer Effizienz und setzen auf eine enge Zusammenarbeit mit unseren Kund:innen.',

    // Partner Section
    'aboutpage.partner.title': 'Ecotech Styria - Partner',
    'aboutpage.partner.exclusive': 'exklusiver Produktionspartner',
    'aboutpage.partner.ecotech.subtitle': 'Fest-Flüssig-Trennung',
    'aboutpage.partner.ecotech.bullet1': 'F&E',
    'aboutpage.partner.ecotech.bullet2': 'Produktmanagement',
    'aboutpage.partner.ecotech.bullet3': 'Vertrieb',
    'aboutpage.partner.ecotech.bullet4': 'Kundendienst',
    'aboutpage.partner.pauger.subtitle': 'Engineering & Produktion',
    'aboutpage.partner.pauger.bullet1': 'Engineering & Design',
    'aboutpage.partner.pauger.bullet2': 'Produktion von Maschinen und Komponenten',
    'aboutpage.partner.pauger.bullet3': 'Ersatzteillager',

    'aboutpage.contact.title': 'Kontakt',
    'aboutpage.location.title': 'Standort',
    'aboutpage.careers.badge': 'Karriere',
    'aboutpage.careers.title': 'Karriere bei uns',
    'aboutpage.careers.intro': 'Wir entwickeln technologisch führende Lösungen für die Trennung von flüssigen und festen Stoffen. Als innovatives Unternehmen im Maschinenbau sowie in der Umwelt- und Landtechnik realisieren wir effiziente Maschinen und technische Systeme für die fest-flüssig Trennung.',
    'aboutpage.careers.intro2': 'Ob Konstruktion, Entwicklung, Fertigung, Service, Projektmanagement oder Vertrieb – du bist Teil technisch anspruchsvoller Projekte mit klarer Verantwortung, kurzen Entscheidungswegen und direktem Kundenbezug.',
    'aboutpage.careers.tagline': 'Gestalten Sie mit uns leistungsfähige Technik für nachhaltige Prozesse.',
    'aboutpage.careers.ctaLabel': 'Initiativbewerbung senden',

    // Sales Page
    'sales.findPartner.title': 'Vertriebspartner finden',
    'sales.findPartner.desc': 'Finden Sie unseren Vertriebspartner für Ihre Region. Unsere Vertriebspartner sind spezialisiert auf Separationstechnologie und stehen Ihnen mit Beratung und Service zur Seite.',
    'sales.becomePartner.title': 'Sie möchten unser Vertriebspartner werden?',
    'sales.spareparts.title': 'Ersatzteile',
    'sales.spareparts.desc': 'Wir bieten ein umfassendes Sortiment an Ersatzteilen für alle unsere Maschinen. Kontaktieren Sie uns für ein Angebot.',
    'sales.service.title': 'Service',
    'sales.service.desc': 'Unser erfahrenes Service-Team steht Ihnen bei Wartung, Reparatur und technischer Unterstützung zur Verfügung.',

    // Products Page
    'productpage.bg2.title': 'Filterschneckenpresse BGII-800',
    'productpage.bg2.desc': 'Die Filterschneckenpresse BGII-800 ist unsere Flaggschiff-Maschine. Mit patentierter Geometrie und automatischer Wascheinrichtung bietet sie optimale Effizienz und minimalen Verschleiß.',

    // BG2 PDF Content
    'productpage.bg2.applications.ind.title': 'Anwendungen Industrie',
    'productpage.bg2.applications.ind.items': 'Kunststoffrecycling|Pulp & Paper|Schlachthofabwässer|Kommunale Abwässer|Lebensmittelverarbeitung|Fasersuspensionen',
    'productpage.bg2.applications.agr.title': 'Anwendungen Landwirtschaft',
    'productpage.bg2.applications.agr.items': 'Gülle von Nutztieren|Gärreste aus Biogasanlagen',
    'productpage.bg2.benefits.title': 'Vorteile',
    'productpage.bg2.benefits.items': 'Reduktion von Entsorgungskosten|Wiederverwendung der Feststoffe|Wiederverwendung der flüssigen Phase|Einfacheres Nährstoffmanagement|Höhere Prozesseffizienz',
    'productpage.bg2.features.title': 'Merkmale',
    'productpage.bg2.features.items': 'Edelstahl-Konstruktion|Geringer Spalt zwischen Sieb und Schnecke|Bis zu 1,2 bar Zulaufdruck|Geschlossenes System, automatische Wascheinrichtung|Steuerungen mit offener Schnittstelle (ProfiNet etc.) für einfache Einbindung|Verminderter Verschleiß und höherer Durchsatz durch patentierte Schneckengeometrie und Stützkonstruktion im Pressbereich|Vollautomatische Regelung des Trockensubstanz-Gehaltes im Feststoff|Überwachung des Betriebszustands (Variation im Zulauf, Leckagen, Drehmoment, Ölqualität etc.)|Höchst abrasionsbeständige Schneckenbeschichtung',
    'productpage.bg2.tech.title': 'Technische Daten',
    'productpage.bg2.tech.drive': 'Antriebsleistung',
    'productpage.bg2.tech.drive.val': '5,5 - 15,0 kW\n(7,5 - 20,0 PS)',
    'productpage.bg2.tech.throughput': 'Durchsatz',
    'productpage.bg2.tech.throughput.val': 'bis zu 75 m³/h',
    'productpage.bg2.tech.gap': 'Spaltweite',
    'productpage.bg2.tech.gap.val': '100 - 1000 µm',
    'productpage.bg2.tech.dry_org': 'Trockensubstanz Organische Fasern',
    'productpage.bg2.tech.dry_org.val': 'bis zu 40%',
    'productpage.bg2.tech.dry_inorg': 'Trockensubstanz Anorganische Fasern',
    'productpage.bg2.tech.dry_inorg.val': 'bis zu 85%',
    'productpage.bg2.tech.trimeter': 'Zulaufdruck',
    'productpage.bg2.tech.trimeter.val': 'bis zu 1,2 bar',
    'productpage.bg2.tech.disclaimer': 'Die Leistungsdaten hängen von Zusammensetzung und Viskosität des zu separierenden Mediums ab.',
    'productpage.bgi400.title': 'Filterschneckenpresse BGI-400',
    'productpage.bgi400.desc': 'Die kompakte Filterschneckenpresse BGI-400 ist die wirtschaftliche Lösung für Stoffströme bis ca. 20 m³/h. Plug-and-Play-Inbetriebnahme, hoher Trockensubstanzgehalt im Feststoff und Edelstahlkonstruktion machen sie zur ersten Wahl für Gülle- und Gärrestseparation, Einstreuproduktion sowie kompakte Industrieanwendungen.',
    'productpage.bgi400.availability': 'Kompaktlösung',

    // USP Section
    'productpage.usp.title': 'USP – Patentierte Technologie',
    'productpage.usp.1.title': 'Patentierte Filterschneckengeometrie',
    'productpage.usp.1.desc': 'Die patentierte Filterschneckengeometrie mit zusätzlichen Schneckenflügeln im Filterbereich sorgt für gesteigerten spezifischen Durchsatz und verringerten Verschleiß.',
    'productpage.usp.2.title': 'Patentiertes Stützgehäuse',
    'productpage.usp.2.desc': 'Das patentierte Stützgehäuse stützt den Presssieb und absorbiert den Berstdruck. Ermöglicht höheren Pressdruck und damit höheren TS-Gehalt im Feststoff bei reduziertem Verschleiß.',
    'productpage.usp.3.title': 'Automatische TS-Regelung',
    'productpage.usp.3.desc': 'Die automatische TS-Regelung reagiert auf Änderungen in Zulaufmenge und -konsistenz. Erhöht die Prozesssicherheit und ermöglicht konstanten Betriebszustand.',
    'productpage.usp.4.title': 'Vollautomatische Wascheinrichtung',
    'productpage.usp.4.desc': '360° Sprühdüsen verhindern Anhaftungen und Verstopfungen an den Siebkörben. Arbeitet in automatischen Intervallen oder bei händischer Betätigung.',
    'productpage.voreindicker.title': 'Voreindicker / Pre-Thickener',
    'productpage.voreindicker.desc': 'Weitere Informationen zu unserem Voreindicker folgen in Kürze. Kontaktieren Sie uns für Details.',
    'productpage.voreindicker.tagline': 'Demnächst verfügbar',
    'productpage.voreindicker.intro': 'Unser neuer Voreindicker erweitert die Filterschneckenpressen-Familie. Technische Daten und Datenblätter folgen in Kürze.',
    'productpage.comingSoon': 'Coming Soon',
    'productpage.circulyizer.title': 'Circulyzer',
    'productpage.circulyizer.badge': 'Powered by Ecotexteria',
    'productpage.circulyizer.desc': 'Kompakte Separationseinheit für die nasse Dichtesortierung und Wäsche verschiedener Rückstände und Abfallgemische.',
    'productpage.circulyizer.tagline': 'Nasse Dichteseparation',
    'productpage.circulyizer.intro': 'Die Circulyzer Separationseinheit ist ein kompaktes System für die nasse Dichtesortierung und Wäsche verschiedener Rückstände und Abfallgemische. Das vollautomatische Modul im Containerdesign eignet sich besonders für die Aufbereitung von Kunststoff/Kunststoff-, Kunststoff/Metall- und Kunststoff/Papier-Gemischen. Neben der Separation können die aufbereiteten Materialien auch gewaschen werden.',
    'productpage.circulyizer.features.title': 'Merkmale',
    'productpage.circulyizer.features': 'Schwimm-Sink-Trennung im Zentrifugalkraftfeld – rein zylindrischer Zyklon (Röhre)|Keine rotierenden Teile im Trennaggregat|Trennmediumwirbel (z. B. Wasser) wird nur durch Strömung aufgebaut|Direkte Zuführung des Inputmaterials über patentiertes Dosiersystem – keine Dispergierung erforderlich|Erhöhte Verweilzeiten bei mäßigen Strömungsgeschwindigkeiten|Reduzierter Verschleiß und geringer Vordruck erforderlich (0,3 – 0,5 bar)|Vereinfachtes Ersatzteilhandling durch standardisierte Bauteile|Einflussnahme auf Trenneffizienz rasch möglich (3–4 Stellgrößen je nach Ausführung)',
    'productpage.circulyizer.efficiency.title': 'Trenneffizienz',
    'productpage.circulyizer.efficiency.1.label': 'Hartkunststoffe',
    'productpage.circulyizer.efficiency.1.value': '> 99 %',
    'productpage.circulyizer.efficiency.1.desc': 'Produktreinheit möglich',
    'productpage.circulyizer.efficiency.2.label': 'Folien / Fasern',
    'productpage.circulyizer.efficiency.2.value': '> 95 %',
    'productpage.circulyizer.efficiency.2.desc': 'Produktreinheit möglich',
    'productpage.circulyizer.efficiency.3.label': 'Rückgewinnungsrate',
    'productpage.circulyizer.efficiency.3.value': '> 98 %',
    'productpage.circulyizer.efficiency.3.desc': 'für beide Fraktionen möglich',
    'productpage.circulyizer.applications.ind.title': 'Anwendungen Industrie',
    'productpage.circulyizer.applications.ind.items': 'Trennung und Wäsche von Hartkunststoffen (PET, HDPE, techn. Kunststoffe)|Trennung und Wäsche von flexiblen Kunststoffen (Folien)|Wäsche von Kunststoff- und Metallspänen|Abtrennung von metallischen „Verunreinigungen"|Trennung von Kunststoff/Papier- und Kunststoff/Metallmischungen|Vorabscheidung von Schweranteilen|Dispergierung von Partikeln / Fasern',
    'productpage.circulyizer.applications.agr.title': 'Anwendungen Landwirtschaft / Lebensmittelindustrie',
    'productpage.circulyizer.applications.agr.items': 'Wäsche und Trennung von frisch geerntetem Gemüse, Obst etc.|Schonende Wäsche|Mischreaktor für Fest-Flüssig- oder Flüssig/Flüssig-Prozesse',
    'productpage.circulyizer.benefits.title': 'Ihre Vorteile',
    'productpage.circulyizer.benefits.items': 'Auf weniger Platz (nur 6–8 m²), mehr Durchsatz (bis zu 9 t/h) und reiner (bis zu 99,5 % Reinheit) trennen – das ist Effizienz.|Geringes Druckniveau (0,3 – 0,5 bar) ermöglicht geringen spezifischen Energiebedarf von 5 – 10 kWh/t Input.|Statt Bauteilen lassen wir Wasser rotieren – das minimiert Wartung und Störungen.|Schnell anpassbarer Prozess & Design mit Standardbauteilen vereinfachen die Integration.|Das Wesentliche im Blick: Wir überwachen und steuern unsere Anlagen zweckmäßig (Schaufenster, transp. Teilstück …) – für einfache Handhabung und intuitive Bedienung.',
    'productpage.circulyizer.options.title': 'Optionen',
    'productpage.circulyizer.options.items': 'Erweitertes Sensorpaket für Überwachung und Bedienerfreundlichkeit (Redundanz, Kameraüberwachung etc.)|Automatische Verstellbarkeit der Neigung und Einstecktiefe der Dosierspirale|Steuerung High Performance mit abnehmbarem Touchscreen, Browseranbindung, Leistungsmessung und Selbstreinigungsmodus|Steuerungsmodul für Beschickung mit integriertem Überfüllungsschutz|Stahlrahmen nach Kundenwunsch|Einbindung / Überwachung Prozesswassertank|Prozesswassertank inkl. Vorfiltration mittels Schwingsieb|Weitere kundenspezifische Optionen nach Bedarf',
    'productpage.circulyizer.sizes.title': 'Drei Baugrößen',
    'productpage.circulyizer.sizes.desc': 'Der Circulyzer ist in drei Baugrößen erhältlich – abgestimmt auf Durchsatz und Einsatzgebiet. Die detaillierten technischen Daten folgen in Kürze im Datenblatt.',
    'productpage.circulyizer.details.title': 'Konstruktion & Einsatz',
    'productpage.circulyizer.details': 'Für eine effiziente Separation müssen die Materialien vorab auf < 10 – 40 mm zerkleinert werden. Die Integration in eine stabile Rahmenkonstruktion erleichtert Handling, Transport sowie die Installation in neue und bestehende Recyclinganlagen.|Im einfachsten Fall wird Wasser als Trennmedium für die Dichtesortierung verwendet. Je nach Anforderung können auch Salzlösungen, Schlämme oder Wasser-Tensid-Gemische eingesetzt werden.|Der Rahmen besteht aus beschichtetem Schwarzstahl, die medienberührten Teile aus Edelstahl (V4A, 1.4571 oder gleichwertig).',
    'productpage.inquiry': 'Anfrage stellen',
    'productpage.new': 'Neu',
    'productpage.flagship': 'Flaggschiff',
    'productpage.compact': 'Kompakt',
    'productpage.options': 'Optionen',
    'productpage.features': 'Merkmale',
    'productpage.cta.title': 'Individuelle Beratung gewünscht?',
    'productpage.cta.desc': 'Unser Vertriebsteam steht Ihnen für eine persönliche Beratung zur Verfügung.',
    'productpage.cta.find': 'Vertriebspartner finden',
    'productpage.cta.contact': 'Kontakt aufnehmen',

    // Ersatzteile Page
    'ersatzteile.hero.badge': 'Unser Know-how ist Ihre Stärke',
    'ersatzteile.hero.title': 'Ersatzteile in Erstausrüster-Qualität – für maximale Maschinenperformance',
    'ersatzteile.hero.desc': 'Ecotech Styria Ersatzteile stehen für passgenaue Fertigung, hohe Standzeiten und verlässliche Verfügbarkeit. Damit Ihre Anlage dauerhaft wirtschaftlich läuft – mit minimalen Betriebskosten und maximaler Prozesssicherheit.',
    'ersatzteile.hero.cta': 'Kontakt aufnehmen',
    'ersatzteile.hero.cta2': 'Leistungen ansehen',
    'ersatzteile.facts.title': 'Kurzfakten',
    'ersatzteile.facts.1.title': 'Passgenau & einsatzsicher',
    'ersatzteile.facts.1.desc': 'Originalteile nach OE-Standard',
    'ersatzteile.facts.2.title': 'Hohe Standzeiten',
    'ersatzteile.facts.2.desc': 'Material & Fertigung für den Einsatzzweck',
    'ersatzteile.facts.3.title': 'Schnelle Identifizierung',
    'ersatzteile.facts.3.desc': 'Technische Beratung durch Ersatzteilexperten',
    'ersatzteile.facts.4.title': 'Schneckenaufbereitung',
    'ersatzteile.facts.4.desc': 'Instandsetzung & Aufpanzerung für „zweites Leben"',
    'ersatzteile.beratung.title': 'Kompetente Beratung, die den Unterschied macht',
    'ersatzteile.beratung.desc': 'Unsere Ersatzteilexperten unterstützen Sie bei der Identifizierung des passenden Ersatz- oder Verschleißteils. Mit fundierter technischer Beratung sorgen wir dafür, dass Sie schnell und sicher die richtige Lösung erhalten – unkompliziert und zuverlässig.',
    'ersatzteile.beratung.1.title': 'Hilfestellung bei der Teilezuordnung',
    'ersatzteile.beratung.1.desc': 'Sicher, schnell und praxisnah',
    'ersatzteile.beratung.2.title': 'Klare Spezifikationen',
    'ersatzteile.beratung.2.desc': 'Für eine reibungslose Bestellung & kurze Stillstandszeiten',
    'ersatzteile.preis.badge': 'Ihre Vorteile',
    'ersatzteile.preis.title': 'Bestes Preis-Leistungs-Verhältnis',
    'ersatzteile.preis.desc': 'Die Wirtschaftlichkeit Ihrer Anlage wird maßgeblich durch die Qualität der eingesetzten Ersatzteile bestimmt. Ob Siebkorb oder Pressschnecke – originale Ecotech Styria Ersatzteile liefern nachhaltige Vorteile im Betrieb.',
    'ersatzteile.preis.1.title': 'Längere Lebensdauer',
    'ersatzteile.preis.1.desc': 'Im Vergleich zu Nachbauteilen deutlich höhere Standzeiten',
    'ersatzteile.preis.2.title': 'Weniger Wartungsaufwand',
    'ersatzteile.preis.2.desc': 'Reduzierte Stillstände und geringere Instandhaltungskosten',
    'ersatzteile.preis.3.title': 'Höhere Maschinenverfügbarkeit',
    'ersatzteile.preis.3.desc': 'Maximale Performance bei minimalen Betriebskosten',
    'ersatzteile.schnecken.badge': 'Service',
    'ersatzteile.schnecken.title': 'Aufbereitung von Schnecken – Qualität im Kern des Separators',
    'ersatzteile.schnecken.desc1': 'Schnecken sind die zentralen Funktionselemente in Separatoren – ihre Qualität ist entscheidend für Leistungsfähigkeit, Standzeit und Wirtschaftlichkeit der gesamten Maschine. Entscheidend sind dabei exakt eingehaltene Toleranzen, eine prozesssichere Geometrie sowie die fachgerechte Aufpanzerung mit geeigneten Verfahren und Werkstoffen für maximale Verschleißfestigkeit.',
    'ersatzteile.schnecken.desc2': 'Ecotech Styria bietet die professionelle Aufbereitung Ihrer Pressschnecke an. Durch gezielte Instandsetzung, Anpassung der Geometrie und erneute Verschleißbeschichtung verleihen wir Ihrer Schnecke ein zweites Leben – wirtschaftlich, nachhaltig und in bewährter Ecotech-Styria-Qualität. Ecotech Styria bietet auch Ersatzschnecken für Fremdfabrikate an – gerne bearbeiten wir hier Ihre Anfrage.',
    'ersatzteile.schnecken.1': 'Präzise Toleranzen — Für stabile Prozesse und reproduzierbare Performance',
    'ersatzteile.schnecken.2': 'Aufpanzerung mit passenden Verfahren — Werkstoff & Methode für hohe Verschleißfestigkeit',
    'ersatzteile.schnecken.3': '„Zweites Leben" für Ihre Pressschnecke — Professionelle Instandsetzung statt teurer Neuanschaffung',
    'ersatzteile.oem.title': 'Erstausrüster-Qualität über die gesamte Maschinenlebensdauer',
    'ersatzteile.oem.desc': 'Unsere Ersatz- und Verschleißteile werden gemeinsam mit der Originalausrüstung entwickelt und gefertigt. Sie sind 100% passgenau, einsatzsicher und erfüllen dieselben hohen Qualitätsanforderungen wie die Erstausrüstung.',
    'ersatzteile.tech.title': 'Immer am aktuellen Stand der Technik',
    'ersatzteile.tech.desc': 'Die kontinuierliche Weiterentwicklung unserer Produkte ist Teil unseres Selbstverständnisses. Dieses Know-how fließt selbstverständlich auch in unsere Ersatz- und Verschleißteile ein – für zukunftssichere Lösungen und dauerhaft hohe Anlagenperformance.',
    'ersatzteile.contact.title': 'Schnell zum richtigen Teil – mit unserem Service',
    'ersatzteile.contact.desc': 'Senden Sie uns Ihre Maschinen- bzw. Teileinformationen – wir unterstützen Sie bei der Identifizierung und erstellen ein passendes Angebot. Auf Wunsch inkl. Schneckenaufbereitung.',
    'ersatzteile.contact.cta': 'E-Mail senden',
    'ersatzteile.contact.box.title': 'Ihr Kontakt für Ersatzteile',

    // Service Page
    'service.hero.badge': 'Vor-Ort-Service · Planbar · Schnell',
    'service.hero.title': 'Professionelle Wartung mit Ecotech Styria',
    'service.hero.desc': 'Regelmäßige Wartung reduziert ungeplante Stillstände, erhält den Maschinenwert und verhindert Folgeschäden. Unsere Servicetechniker unterstützen Sie effizient und praxisnah – direkt bei Ihnen im Betrieb.',
    'service.hero.cta': 'Service kontaktieren',
    'service.facts.title': 'Kurzfakten',
    'service.facts.1': 'Vor-Ort-Service mit modern ausgestatteten Servicefahrzeugen',
    'service.facts.2': 'Erfahrene und geschulte Servicetechniker',
    'service.facts.3': 'Wartung & Instandhaltung – planbar und dokumentiert',
    'service.facts.4': 'Option: schlüsselfertige Installation & Inbetriebnahme',
    'service.regular.title': 'Regelmäßiger Service – weniger Stillstand, mehr Sicherheit',
    'service.regular.desc': 'Regelmäßig gewartete Maschinen arbeiten stabiler, effizienter und verursachen weniger ungeplante Ausfälle. Gleichzeitig bleibt der Maschinenwert langfristig erhalten.',
    'service.regular.1': 'Ungeplante Ausfallzeiten minimieren',
    'service.regular.2': 'Maschinenwert langfristig erhalten',
    'service.regular.3': 'Internen Wartungsaufwand reduzieren',
    'service.regular.4': 'Kalkulierbare, transparente Servicekosten sicherstellen',
    'service.install.title': 'Schlüsselfertige Installation & Inbetriebnahme',
    'service.install.desc': 'Auf Wunsch übernehmen wir die Installation und Inbetriebnahme Ihrer neuen Maschine oder Anlage – inklusive Einschulung für effizientes und sicheres Arbeiten.',
    'service.install.1': 'Fachgerechte Montage und saubere Integration in den Prozess',
    'service.install.2': 'Inbetriebnahme & Funktionsprüfung nach definierten Standards',
    'service.install.3': 'Einschulung des Bedienpersonals für sicheren, effizienten Betrieb',
    'service.install.cta': 'Jetzt anfragen',

    // Sales Page
    'sales.partner.label': 'Partnernetzwerk',
    'sales.partner.country.title': 'Land wählen',
    'sales.partner.country.all': 'Alle Länder',
    'sales.partner.empty.title': 'Kein Vertriebspartner in diesem Land',
    'sales.partner.empty.desc': 'In dieser Region haben wir aktuell keinen Vertriebspartner. Wenden Sie sich gerne direkt an unsere Zentrale – wir unterstützen Sie persönlich.',
    'sales.partner.empty.cta': 'Direkt Kontakt aufnehmen',
    'sales.partner.notfound.title': 'Sie haben keinen passenden Vertriebspartner gefunden?',
    'sales.partner.notfound.desc': 'Dann wenden Sie sich gerne direkt an unsere Zentrale – wir helfen Ihnen weiter.',
    'sales.partner.notfound.cta': 'Kontakt herstellen',
    'sales.partner.become.title': 'Sie möchten unser Vertriebspartner werden?',
    'sales.partner.become.desc': 'Werden Sie Teil unseres Vertriebsnetzwerks und profitieren Sie von unserer Expertise in der Separationstechnologie.',
    'sales.partner.become.cta': 'Partner werden',
    'sales.partner.contact': 'Ansprechpartner Vertrieb:',
    'sales.form.company': 'Unternehmen',
    'sales.form.phone': 'Telefon',
    'sales.form.placeholder': 'Erzählen Sie uns von Ihrem Unternehmen und Ihrer Region...',
    'sales.service.support': 'Support',
    'sales.service.items': 'Wartung|Regelmäßige Inspektion und Wartung Ihrer Anlagen|Reparatur|Schnelle und zuverlässige Reparaturleistungen|Technische Beratung|Expertenwissen für Ihre Separationsprozesse|Inbetriebnahme|Professionelle Installation und Einweisung',

    // Integration Page
    'integration.hero.title': 'Systemintegration – Installation und Inbetriebnahme',
    'integration.hero.subtitle': 'Alles aus einer Hand – von der Idee bis zur Umsetzung.',

    'integration.overview.badge': 'Installation & Inbetriebnahme',
    'integration.overview.title': 'Alles aus einer Hand – von der Idee bis zur Umsetzung',
    'integration.overview.p1': 'Ecotech Styria sieht sich als gesamtheitlicher Partner für Ihre Anlage. Auf Wunsch planen wir die Maschinenintegration in Ihre Anlage und übernehmen ebenso Installation sowie Inbetriebnahme – koordiniert, effizient und mit Fokus auf Wirtschaftlichkeit.',
    'integration.overview.p2.bold': 'Sie kümmern sich um Ihr Geschäft',
    'integration.overview.p2.rest': ' – Ecotech Styria kümmert sich um die Optimierung Ihrer Anlage: abgestimmte Schnittstellen, sauberer Hochlauf und ein stabiler Aufbereitungsprozess von Beginn an.',

    'integration.priorities.title': 'Prioritäten',
    'integration.priorities.intro': 'Worauf wir bei Installation & Inbetriebnahme konsequent hin optimieren:',
    'integration.priorities.1.title': 'Hohe Anlagenverfügbarkeit',
    'integration.priorities.1.desc': 'robuster Aufbau & klarer Hochlauf',
    'integration.priorities.2.title': 'Niedrigste Aufbereitungskosten',
    'integration.priorities.2.desc': 'minimale Energie- & Verschleißkosten',
    'integration.priorities.3.title': 'Wartungsfreundliches Design',
    'integration.priorities.3.desc': 'zugängliche Komponenten & Service-Fokus',
    'integration.priorities.4.title': 'Prozessstabilität',
    'integration.priorities.4.desc': 'saubere Integration & zuverlässige Übergabe',

    'integration.leistung.title': 'Unsere Leistung – von Planung bis Hochlauf',
    'integration.leistung.intro': 'Wir übernehmen die komplette Maschinenintegration und führen Installation sowie Inbetriebnahme strukturiert durch. Damit funktionieren Komponenten und Prozessstufen im Zusammenspiel – optimiert auf Materialstrom, Durchsatz und Wirtschaftlichkeit.',
    'integration.leistung.1.title': 'Integrationsplanung',
    'integration.leistung.1.desc': 'Schnittstellen, Aufstellplanung, Medien & Peripherie – sauber definiert.',
    'integration.leistung.2.title': 'Installation & Montagekoordination',
    'integration.leistung.2.desc': 'Terminsicher, sicherheitskonform und mit klarem Verantwortungsmodell.',
    'integration.leistung.3.title': 'Inbetriebnahme & Prozess-Hochlauf',
    'integration.leistung.3.desc': 'Parametrierung, Funktionschecks und stabiler Aufbereitungsprozess ab Tag 1.',
    'integration.leistung.4.title': 'Übergabe & Optimierung',
    'integration.leistung.4.desc': 'Dokumentation, Schulung und Feintuning für maximale Wirtschaftlichkeit.',

    'integration.partner.title': 'Leistungspaket über Partnernetzwerk',
    'integration.partner.intro': 'Ecotech Styria kann über seine Partner alle nötigen Leistungen anbieten – abgestimmt, koordiniert und mit einem Ansprechpartner für Sie.',
    'integration.partner.1.title': 'Stahlbau',
    'integration.partner.1.desc': 'Konstruktion, Bühnen, Gestelle, Schutz- und Servicezugänge.',
    'integration.partner.2.title': 'Steuerungsentwicklung',
    'integration.partner.2.desc': 'Automatisierung, Visualisierung, Schnittstellen & Sicherheitskonzept.',
    'integration.partner.3.title': 'Montage',
    'integration.partner.3.desc': 'Mechanik, Verrohrung, Medienanbindung – sauber dokumentiert.',
    'integration.partner.4.title': 'Inbetriebnahme',
    'integration.partner.4.desc': 'Abnahmen, Testläufe, Parameter-Setups und Prozessstabilisierung.',
    'integration.partner.vorteil.label': 'Ihr Vorteil:',
    'integration.partner.vorteil.text': 'Ein klarer Projektablauf mit definierten Meilensteinen – von der Integration bis zur stabil laufenden Anlage.',

    'integration.cta.title': 'Sie möchten Ihre Anlage optimieren, schlüsselfertig kaufen und rasch in Betrieb nehmen?',
    'integration.cta.desc': 'Wir unterstützen von Planung bis Hochlauf – abgestimmt auf Ihren Stoffstrom und Ihre Wirtschaftlichkeitsziele.',
    'integration.cta.button': 'Kontakt aufnehmen',

    'integration.kontakt.title': 'Kontakt',
    'integration.kontakt.text': 'Schreiben Sie uns Ihre Eckdaten (Material, Durchsatz, Bestandssituation, Zielsetzung) – wir melden uns mit einem klaren Integrations- und Inbetriebnahmeplan.',

    // Agriculture Page
    'agriculture.title': 'Landwirtschaft',
    'agriculture.subtitle': 'Effiziente Separationstechnologie für Gülle von Nutztieren und Gärreste aus Biogasanlagen.',
    'agriculture.intro.title': 'Maßgeschneiderte Lösungen für die',
    'agriculture.intro.highlight': 'Landwirtschaft',
    'agriculture.intro.desc': 'In der modernen Landwirtschaft ist der effiziente Umgang mit Nährstoffen und Abfallprodukten entscheidend für Produktivität und Nachhaltigkeit. Unsere EcoTech Filterschneckenpressen bieten bewährte, robuste und hochgradig effiziente Lösungen für die Trennung von festen und flüssigen Bestandteilen.',
    'agriculture.manure.title': 'Gülle von Nutztieren',
    'agriculture.manure.desc': 'Die Separation von Rinder- oder Schweinegülle reduziert das Lagervolumen der flüssigen Phase signifikant. Der gewonnene Feststoff eignet sich hervorragend als Dünger, während die flüssige Phase leichter auf die Felder ausgebracht werden kann.',
    'agriculture.manure.points': 'Volumenreduktion um bis zu 30%|Leichtere Ausbringung der dünnen Phase|Geruchsminderung|Feststoff als hochwertiger Kompost oder Einstreu nutzbar',
    'agriculture.biogas.title': 'Gärreste aus Biogasanlagen',
    'agriculture.biogas.desc': 'Biogasanlagen profitieren massiv von einer effizienten Separierung der Gärreste. Dies verbessert die Nährstofflogistik, verringert Transportkosten und optimiert den weiteren Betriebsablauf.',
    'agriculture.biogas.points': 'Optimierung der Nährstofflogistik|Reduzierung von Transport- und Lagerkosten|Homogenere flüssige Phase für besseres Handling|Verkaufsfähiger Festdünger',
    'agriculture.findProduct': 'Passendes Produkt finden',
    'agriculture.cta.title': 'Sind Sie bereit für die Separation der nächsten Generation?',
    'agriculture.cta.desc': 'Kontaktieren Sie uns für eine kostenlose technische Beratung und finden Sie heraus, wie unsere Filterschneckenpressen Ihren Betrieb optimieren können.',
    'agriculture.cta.button': 'Beratungstermin vereinbaren',

    // Applications Page
    'applications.findProduct': 'Passendes Produkt finden',
    'applications.page.subtitle': 'Entdecken Sie die vielfältigen Einsatzbereiche unserer Separationstechnologie – von der Landwirtschaft bis zur Lebensmittelindustrie.',
    'productpage.bg2.options': 'Automatische Wascheinrichtung für Filter- und Presssieb|Sensorpakete zur Überwachung|Steuerung ECO mit manueller Regelung|Steuerung PRO mit HMI-Panel und ProfiNET|Zulaufverrohrung mit Teleskoprohr|Steuerungsmodul für Zulaufpumpen|Zusätzlicher Fußrahmen für höhere Arbeitshöhe|Kundenspezifische Optionen nach Bedarf',
    'productpage.bgi400.features': 'Kompaktbauweise – ideal für kleinere Prozessströme bis ca. 20 m³/h|Optimale Lösung für landwirtschaftliche Anwendungen und Agraranlagen|Hoher TS-Gehalt im Feststoff – geeignet für hochwertige Einstreu|Einfache Plug&Play-Lösung mit angebautem Frequenzumrichter|Ausführung in Edelstahl (1.4301 / AISI 304)|Edelstahlschnecke mit Panzerung|Edelstahl-Spaltsiebe|Zulaufdruck bis 1,2 bar|Zulaufverrohrung mit Teleskoprohr und Überlaufrohr',
    'productpage.subtitle': 'Entdecken Sie unsere innovativen Separationslösungen für maximale Effizienz und Langlebigkeit.',

    // News Page
    'newspage.title': 'News & Medien',
    'newspage.hero.subtitle': 'Bleiben Sie auf dem Laufenden über Neuigkeiten, Erfolgsgeschichten und Entwicklungen bei EcoTech Styria.',
    'newspage.sections.news': 'News & Erfolgsgeschichten',
    'newspage.sections.events': 'Messen & Events',
    'newspage.downloads.title': 'Download',
    'newspage.downloads.desc': 'Bilder, Renderings, Prospekte',
    'newspage.downloads.text': 'Laden Sie unsere Produktbroschüren, technischen Datenblätter und Bilder herunter.',
    'newspage.download.brochureBg2': 'Produktbroschüre BGII-800',
    'newspage.download.brochureBgi400': 'Produktbroschüre BGI-400',
    'newspage.download.datasheetBg2': 'Technisches Datenblatt BGII-800',
    'newspage.download.datasheetBgi400': 'Technisches Datenblatt BGI-400',
    'newspage.download.imagesBg2': 'Produktbilder BGII-800',
    'newspage.download.imagesBgi400': 'Produktbilder BGI-400',
    'newspage.download.recyclingSheet': 'Anwendungsblatt Kunststoffrecycling',
    'newspage.readMore': 'Weiterlesen',
    'newspage.showLess': 'Weniger anzeigen',
    'newspage.eventReadMore': 'Mehr erfahren',

    // Home Page section labels
    'home.sections.applications': 'Bereiche',
    'home.sections.products': 'Produkte',
    'home.sections.benefits': 'Vorteile',
    'home.sections.news': 'Aktuelles',

    // About Page section labels
    'aboutpage.team.label': 'Team',
    'aboutpage.contact.label': 'Kontakt',
    'aboutpage.location.label': 'Standort',
    'aboutpage.contact.formSuccess': 'Vielen Dank für Ihre Nachricht! Wir werden uns bald bei Ihnen melden.',

    // Sales Page – Spare Parts preview
    'salespage.spareparts.label': 'Ersatzteile',
    'salespage.spareparts.title': 'Originale Ersatzteile — für maximale Maschinenperformance',
    'salespage.spareparts.desc': 'Ecotech Styria Ersatzteile stehen für passgenaue Fertigung, hohe Standzeiten und verlässliche Verfügbarkeit. Damit Ihre Anlage dauerhaft wirtschaftlich läuft – mit minimalen Betriebskosten und maximaler Prozesssicherheit.',
    'salespage.spareparts.highlight1': 'Erstausrüster-Qualität — passgenau, langlebig, einsatzsicher',
    'salespage.spareparts.highlight2': 'Schneckenaufbereitung — „zweites Leben" für Ihre Pressschnecke',
    'salespage.spareparts.highlight3': 'Kompetente Beratung bei Identifizierung & Bestellung',
    'salespage.spareparts.highlight4': 'Kurze Lieferzeiten direkt vom Hersteller',
    'salespage.spareparts.cta': 'Alle Leistungen ansehen',
    'salespage.schnecken.title': 'Aufbereitung von Schnecken — Qualität im Kern des Separators',
    'salespage.schnecken.desc': 'Schnecken sind die zentralen Funktionselemente in Separatoren. Ecotech Styria bietet die professionelle Aufbereitung Ihrer Pressschnecke an: gezielte Instandsetzung, Anpassung der Geometrie und erneute Verschleißbeschichtung – für ein zweites Leben Ihrer Schnecke.',
    'salespage.schnecken.cta': 'Mehr über Schneckenaufbereitung',

    // Sales Page – Service preview
    'salespage.service.label': 'Service & Inbetriebnahme',
    'salespage.service.title': 'Professionelle Wartung mit Ecotech Styria',
    'salespage.service.desc': 'Regelmäßig gewartete Maschinen sind zuverlässiger und haben weniger ungeplante Ausfälle. Schnelle und kompetente Unterstützung durch unsere erfahrenen Servicetechniker — direkt bei Ihnen im Betrieb.',
    'salespage.service.benefit1': 'Ungeplante Ausfallzeiten minimieren',
    'salespage.service.benefit2': 'Maschinenwert langfristig erhalten',
    'salespage.service.benefit3': 'Internen Wartungsaufwand reduzieren',
    'salespage.service.benefit4': 'Kalkulierbare, transparente Servicekosten',
    'salespage.service.cta': 'Service-Leistungen ansehen',
    'salespage.install.title': 'Schlüsselfertige Installation & Inbetriebnahme',
    'salespage.install.desc': 'Auf Wunsch übernehmen wir Installation und Inbetriebnahme Ihrer neuen Maschine oder Anlage – inklusive Einschulung für effizientes und sicheres Arbeiten.',
    'salespage.install.cta': 'Mehr zum Service',

    // Products Page – BGI-400 technical data
    'productpage.bgi400.tech.title': 'Technische Daten',
    'productpage.bgi400.tech.drive': 'Antriebsleistung',
    'productpage.bgi400.tech.drive.val': '2,2 - 3,0 kW\n(3,0 - 4,0 PS)',
    'productpage.bgi400.tech.throughput': 'Durchsatz',
    'productpage.bgi400.tech.throughput.val': 'bis zu 20 m³/h',
    'productpage.bgi400.tech.gap': 'Spaltweite',
    'productpage.bgi400.tech.gap.val': '100 - 1000 µm',
    'productpage.bgi400.tech.dry_org': 'TS-Gehalt organische Fasern',
    'productpage.bgi400.tech.dry_org.val': 'bis zu 42%',
    'productpage.bgi400.tech.dry_inorg': 'TS-Gehalt anorganische Fasern',
    'productpage.bgi400.tech.dry_inorg.val': 'bis zu 85%',
    'productpage.bgi400.tech.pressure': 'Zulaufdruck',
    'productpage.bgi400.tech.pressure.val': 'bis zu 1,2 bar',
    'productpage.bgi400.tech.disclaimer': 'Die Leistungsdaten hängen von Zusammensetzung und Viskosität des zu separierenden Mediums ab.',

    // BGI-400 Plug & Play (new 2026-04-20)
    'productpage.bgi400pnp.title': 'BGI-400 Plug & Play',
    'productpage.bgi400pnp.badge': 'Mobil',
    'productpage.bgi400pnp.desc': 'Die mobile Plug & Play-Variante unserer kompakten Filterschneckenpresse BGI-400 – dieselbe bewährte Technik in einer vorkonfektionierten, standortflexiblen Einheit. Einfach anschließen, aufstellen und in Betrieb nehmen.',
    'productpage.bgi400pnp.features': 'Mobile Einheit – ohne Fundament einsatzbereit|Automatische Drucküberwachung|Stahlbau verzinkt – langlebig und wetterfest|Integrierte Drehkolbenpumpe',

    // Header / Footer extras
    'nav.languageLabel': 'Sprache:',
    'footer.social': 'Social Media',
    'footer.links': 'Links',
    'footer.navigation': 'Navigation',
    'footer.rights': 'Alle Rechte vorbehalten.',

    // Legal Pages
    'legal.terms.title': 'Allgemeine Geschäftsbedingungen',
    'legal.terms.label': 'Rechtliches',
    'legal.terms.1.title': '1. Geltungsbereich',
    'legal.terms.1.body': 'Diese Allgemeinen Geschäftsbedingungen gelten für alle Lieferungen und Leistungen der EcoTech Styria GmbH an ihre Kunden.',
    'legal.terms.2.title': '2. Vertragsschluss',
    'legal.terms.2.body': 'Ein Vertrag kommt durch schriftliche Auftragsbestätigung oder durch Ausführung des Auftrags zustande.',
    'legal.terms.3.title': '3. Preise und Zahlungsbedingungen',
    'legal.terms.3.body': 'Alle Preise verstehen sich in Euro zuzüglich der gesetzlichen Mehrwertsteuer. Zahlungen sind innerhalb von 14 Tagen nach Rechnungsstellung fällig.',
    'legal.terms.4.title': '4. Lieferung',
    'legal.terms.4.body': 'Liefertermine werden nach bestem Wissen angegeben, sind jedoch unverbindlich, sofern nicht ausdrücklich als verbindlich vereinbart.',
    'legal.terms.5.title': '5. Gewährleistung',
    'legal.terms.5.body': 'Die Gewährleistungsfrist beträgt 12 Monate ab Übergabe der Ware. Für gebrauchte Ware wird keine Gewährleistung übernommen.',
    'legal.terms.6.title': '6. Haftung',
    'legal.terms.6.body': 'Die Haftung für leichte Fahrlässigkeit ist ausgeschlossen, soweit keine vertragswesentlichen Pflichten verletzt werden.',
    'legal.terms.7.title': '7. Eigentumsvorbehalt',
    'legal.terms.7.body': 'Die gelieferte Ware bleibt bis zur vollständigen Bezahlung Eigentum der EcoTech Styria GmbH.',
    'legal.terms.8.title': '8. Gerichtsstand',
    'legal.terms.8.body': 'Gerichtsstand ist Graz. Es gilt österreichisches Recht unter Ausschluss des UN-Kaufrechts.',

    'legal.privacy.title': 'Datenschutzerklärung',
    'legal.privacy.label': 'Datenschutz',
    'legal.privacy.1.title': 'Verantwortlicher',
    'legal.privacy.1.body': 'EcoTech Styria GmbH\nJudenburgerstraße 176\nA-8580 Köflach, Österreich\nE-Mail: office@ecotechstyria.com',
    'legal.privacy.2.title': 'Erhebung und Verarbeitung personenbezogener Daten',
    'legal.privacy.2.body': 'Wir erheben und verarbeiten personenbezogene Daten nur, soweit dies für die Bereitstellung unserer Dienstleistungen erforderlich ist. Dies umfasst Kontaktdaten für Anfragen und Bestellungen.',
    'legal.privacy.3.title': 'Zweck der Datenverarbeitung',
    'legal.privacy.3.body': 'Die erhobenen Daten werden verwendet zur Bearbeitung von Anfragen, Auftragsabwicklung, sowie zur Kommunikation mit unseren Kunden und Partnern.',
    'legal.privacy.4.title': 'Rechtsgrundlage',
    'legal.privacy.4.body': 'Die Verarbeitung erfolgt auf Grundlage von Art. 6 DSGVO (Vertragserfüllung, berechtigtes Interesse, Einwilligung).',
    'legal.privacy.5.title': 'Datensicherheit',
    'legal.privacy.5.body': 'Wir setzen technische und organisatorische Maßnahmen ein, um Ihre Daten gegen Manipulation, Verlust, Zerstörung oder Zugriff unberechtigter Personen zu schützen.',
    'legal.privacy.6.title': 'Ihre Rechte',
    'legal.privacy.6.body': 'Sie haben das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch. Kontaktieren Sie uns unter office@ecotechstyria.com.',
    'legal.privacy.7.title': 'Cookies',
    'legal.privacy.7.body': 'Unsere Website verwendet Cookies ausschließlich zur technischen Funktionsfähigkeit. Es werden keine Tracking-Cookies eingesetzt.',

    'legal.imprint.title': 'Impressum',
    'legal.imprint.label': 'Rechtliches',
    'legal.imprint.company': 'Unternehmensdaten',
    'legal.imprint.legalInfo': 'Rechtliche Informationen',
    'legal.imprint.management': 'Geschäftsführung',
    'legal.imprint.uid': 'UID-Nummer',
    'legal.imprint.fbn': 'Firmenbuchnummer',
    'legal.imprint.fbg': 'Firmenbuchgericht',
    'legal.imprint.fbg.val': 'Landesgericht für Zivilrechtssachen Graz',
    'legal.imprint.member': 'Mitglied bei',
    'legal.imprint.member.val': 'WKO Steiermark',
    'legal.imprint.authority': 'Behörde gem. ECG',
    'legal.imprint.authority.val': 'Bezirkshauptmannschaft Voitsberg',
    'legal.imprint.profession': 'Berufsbezeichnung',
    'legal.imprint.profession.val': 'Mechatroniker für Maschinen- und Fertigungstechnik',

    'legal.dealers.title': 'Unsere Händler',
    'legal.dealers.label': 'Vertrieb',
    'legal.dealers.intro': 'Unsere autorisierten Vertriebspartner stehen Ihnen für Beratung, Verkauf und Service vor Ort zur Verfügung.',
    'legal.dealers.becomeQuestion': 'Möchten Sie ebenfalls Vertriebspartner werden?',
    'legal.dealers.learnMore': 'Mehr erfahren',
    'legal.dealers.country.slovenia': 'Slowenien',
    'legal.dealers.country.austria': 'Österreich',
    'legal.dealers.country.usa': 'USA',

    // Contact Form
    'form.name': 'Name',
    'form.email': 'E-Mail',
    'form.subject': 'Betreff',
    'form.message': 'Nachricht',
    'form.submit': 'Absenden',
    'form.sendApplication': 'Bewerbung senden',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.sales': 'Sales & Aftersales',
    'nav.applications': 'Applications',
    'nav.products': 'Products',
    'nav.integration': 'System Integration',
    'nav.news': 'News & Media',

    // Footer
    'footer.terms': 'Terms & Conditions',
    'footer.privacy': 'Privacy Policy',
    'footer.legal': 'Legal Notice',
    'footer.dealers': 'Dealers',

    // Hero
    'hero.headline': 'Next Level Separation',
    'hero.subheadline': 'Innovative Solid-Liquid Separation Solutions',
    'hero.cta': 'Learn More',

    // About Section
    'about.title': 'About Us',
    'about.description': 'Over 15 years of in-depth expertise in the development and technical realization in mechanical and plant engineering, with a specialized focus on forward-looking separation and environmental technology.',
    'about.link': 'To Company Page',

    // Applications Section
    'applications.title': 'Applications',
    'applications.learnMore': 'Learn More',
    'applications.agriculture.title': 'Agriculture',
    'applications.agriculture.desc': 'Manure from livestock, fermentation residues from biogas plants',
    'applications.bedding.title': 'Green Bedding',
    'applications.bedding.desc': 'Separation for bedding and fertilizer production',
    'applications.biogas.title': 'Biogas',
    'applications.biogas.desc': 'Fermentation residues from biogas plants',
    'applications.recycling.title': 'Plastic Recycling',
    'applications.recycling.desc': 'Wastewater from depacking and plastic recycling plants',
    'applications.municipal.title': 'Municipal',
    'applications.municipal.desc': 'Primary and secondary sludge from sewage treatment plants',
    'applications.paper.title': 'Pulp & Paper',
    'applications.paper.desc': 'Rejects and secondary sludge',
    'applications.mdf.title': 'Process Media & Wastewater',
    'applications.mdf.desc': 'Production wastewater and process media from industrial plants',
    'applications.food.title': 'By-Products & Wastewater',
    'applications.food.desc': 'Slaughterhouse wastewater, washing water, brewery waste and industrial by-products',

    // Products Section
    'products.title': 'Products',
    'products.viewDetails': 'View Details',
    'products.bg2.name': 'Filter Press Screw BGII-800',
    'products.bg2.feature1': 'Up to 75m³/h throughput',
    'products.bg2.feature2': 'Up to 75% dry matter content',
    'products.bg2.feature3': 'Stainless steel construction',
    'products.bgi400.name': 'Filter Press Screw BGI-400',
    'products.bgi400.feature1': 'Up to 20m³/h throughput',
    'products.bgi400.feature2': 'Compact design',
    'products.bgi400.feature3': 'Plug & Play solution',

    // Why Separation Section
    'why.title': 'Why Separation?',
    'why.point1': 'Reduction of storage volume',
    'why.point2': 'Reuse of the solids',
    'why.point3': 'Reduction of disposal costs',
    'why.point4': 'Reuse of the effluent as process water',
    'why.point5': 'Reduction of energy costs',
    'why.point6': 'Reduction of process costs',
    'why.point7': 'Compliance with environmental regulations',
    'why.point8': 'Improved properties of the individual phases after separation',

    // Optimization Section
    'optimization.label': 'Process Optimization',
    'optimization.title': 'Measurably More Efficient',
    'optimization.text': 'We make separation processes measurably more efficient. Through intelligent optimizations, we reduce energy consumption, wear, and operating costs – while simultaneously increasing the performance of existing systems. It does not stop at the analysis: We implement improvements together with our customers consistently and create sustainable added value.',

    // News Section
    'news.title': 'News & Success Stories',
    'news.readMore': 'Read More',

    // About Page
    'aboutpage.intro.title': 'Who Are We?',
    'aboutpage.vision.title': 'Vision & Mission',
    'aboutpage.vision.label': 'Vision:',
    'aboutpage.vision.text': 'To bring separation technology to the next level',
    'aboutpage.slogan.label': 'Slogan:',
    'aboutpage.slogan.text': 'Next Level Separation',
    'aboutpage.mission.label': 'Mission:',
    'aboutpage.mission.text': 'We make separation processes measurably more efficient. Through intelligent optimizations, we reduce energy consumption, wear, and operating costs – while simultaneously increasing the performance of existing systems. It does not stop at the analysis: We implement improvements together with our customers consistently and create sustainable added value.',
    'aboutpage.team.title': 'Our Team',
    'aboutpage.team.ceo.name': 'Heinz Leitner',
    'aboutpage.team.ceo.role': 'CEO',
    'aboutpage.team.ceo.bio': '>15 years of management experience in international environmental technology machinery and plant construction',
    'aboutpage.team.coo.name': 'Gernot Pauger',
    'aboutpage.team.coo.role': 'COO',
    'aboutpage.team.coo.bio': '>15 years of experience in the development and production of special machines for environmental and agricultural technology',
    'aboutpage.team.cto.name': 'Thomas Kampl',
    'aboutpage.team.cto.role': 'CTO',
    'aboutpage.team.cto.bio': '>15 years of experience as an application specialist in separation technology for solid-liquid separation',
    'aboutpage.team.cso.name': 'Günther Pirker',
    'aboutpage.team.cso.role': 'CSO',
    'aboutpage.team.cso.bio': '>15 years of industry experience with focus on production and international sales of agricultural and environmental technology machinery',
    'aboutpage.team.description': 'We are an interdisciplinary team of engineers, application specialists and industry experts united by one goal: to develop technologically leading solutions for the separation of liquid and solid materials. Our approach is system-oriented and solution-focused. We holistically analyze established processing methods, develop customized machine and plant concepts with significantly higher efficiency, and rely on close cooperation with our customers.',

    // Partner Section
    'aboutpage.partner.title': 'Ecotech Styria - Partner',
    'aboutpage.partner.exclusive': 'exclusive Production Partner',
    'aboutpage.partner.ecotech.subtitle': 'Solid-Liquid Separation',
    'aboutpage.partner.ecotech.bullet1': 'R&D',
    'aboutpage.partner.ecotech.bullet2': 'Product Management',
    'aboutpage.partner.ecotech.bullet3': 'Sales',
    'aboutpage.partner.ecotech.bullet4': 'Customer Service',
    'aboutpage.partner.pauger.subtitle': 'Engineering & Production',
    'aboutpage.partner.pauger.bullet1': 'Engineering & Design',
    'aboutpage.partner.pauger.bullet2': 'Production of machines and components',
    'aboutpage.partner.pauger.bullet3': 'Spare parts warehouse',

    'aboutpage.contact.title': 'Contact',
    'aboutpage.location.title': 'Location',
    'aboutpage.careers.badge': 'Careers',
    'aboutpage.careers.title': 'Join our team',
    'aboutpage.careers.intro': 'We develop technologically leading solutions for the separation of liquid and solid materials. As an innovative company in mechanical engineering, environmental technology and agricultural technology, we build efficient machines and technical systems for liquid-solid separation.',
    'aboutpage.careers.intro2': 'Whether engineering, development, manufacturing, service, project management or sales — you are part of technically demanding projects with clear responsibility, short decision paths and direct customer contact.',
    'aboutpage.careers.tagline': 'Shape powerful technology for sustainable processes with us.',
    'aboutpage.careers.ctaLabel': 'Send spontaneous application',

    // Sales Page
    'sales.findPartner.title': 'Find a Sales Partner',
    'sales.findPartner.desc': 'Our sales partners are specialized in separation technology and provide local support and expertise.',
    'sales.becomePartner.title': 'Want to Become a Sales Partner?',
    'sales.spareparts.title': 'Spare Parts',
    'sales.spareparts.desc': 'We offer a comprehensive range of spare parts for all our machines. Contact us for a quote.',
    'sales.service.title': 'Service',
    'sales.service.desc': 'Our experienced service team is available for maintenance, repairs, and technical support.',

    // Products Page
    'productpage.bg2.title': 'Filter Press Screw BGII-800',
    'productpage.bg2.desc': 'The Filter Press Screw BGII-800 is our flagship machine. With patented geometry and automatic washing device, it offers optimal efficiency and minimal wear.',

    // BG2 PDF Content
    'productpage.bg2.applications.ind.title': 'Industrial applications',
    'productpage.bg2.applications.ind.items': 'Plastic recycling|Pulp & Paper|Abattoir waste|Municipal waste water|Food industry|Fiber suspensions',
    'productpage.bg2.applications.agr.title': 'Agricultural applications',
    'productpage.bg2.applications.agr.items': 'Manure from livestock|Digestates from biogas plants',
    'productpage.bg2.benefits.title': 'Benefits',
    'productpage.bg2.benefits.items': 'Reduction of disposal cost|Reuse of solids|Reuse of liquid fraction|Increased nutrient management|Increased process efficiency',
    'productpage.bg2.features.title': 'Key Features',
    'productpage.bg2.features.items': 'Stainless steel construction|Narrow gap between auger and screen|Up to 1.2 bar inlet pressure|Closed system, automatic washing device|Control units with open interface (ProfiNet etc.) for easy implementation|Low wear and increased throughput due to patented auger geometry and special screen basket housing in the pressing zone|Full Auto Control of the dry matter content in the solids|Monitoring of operation status (change in inlet consistency, leakages, torque, oil quality etc.)|Highly abrasion-resistant auger coating',
    'productpage.bg2.tech.title': 'Technical Data',
    'productpage.bg2.tech.drive': 'Drive power',
    'productpage.bg2.tech.drive.val': '5.5 - 15.0 kW\n(7.5 - 20.0 HP)',
    'productpage.bg2.tech.throughput': 'Throughput',
    'productpage.bg2.tech.throughput.val': 'up to 75 m³/h\n(up to 330 gpm)',
    'productpage.bg2.tech.gap': 'Screen slot',
    'productpage.bg2.tech.gap.val': '100 - 1000 µm',
    'productpage.bg2.tech.dry_org': 'Dry matter organic fibers',
    'productpage.bg2.tech.dry_org.val': 'up to 40%',
    'productpage.bg2.tech.dry_inorg': 'Dry matter inorganic fibers',
    'productpage.bg2.tech.dry_inorg.val': 'up to 85%',
    'productpage.bg2.tech.trimeter': 'Feed pressure',
    'productpage.bg2.tech.trimeter.val': 'up to 1.2 bar',
    'productpage.bg2.tech.disclaimer': 'Performance data depends on the consistency and viscosity of the medium to be separated.',
    'productpage.bgi400.title': 'Filter Press Screw BGI-400',
    'productpage.bgi400.desc': 'The compact Filter Press Screw BGI-400 is the economical solution for material streams up to approximately 20 m³/h. Plug-and-play commissioning, high dry matter content in the solids and stainless steel construction make it the first choice for slurry and digestate separation, bedding production and compact industrial applications.',
    'productpage.bgi400.availability': 'Compact Solution',

    // USP Section
    'productpage.usp.title': 'USP – Patented Technology',
    'productpage.usp.1.title': 'Patented Filter Screw Geometry',
    'productpage.usp.1.desc': 'The patented filter screw geometry with additional screw flights in the filter area provides increased specific throughput and reduced wear.',
    'productpage.usp.2.title': 'Patented Support Housing',
    'productpage.usp.2.desc': 'The patented support housing supports the press screen and absorbs burst pressure. Enables higher pressing pressure and thus higher dry matter content in the solids with reduced wear.',
    'productpage.usp.3.title': 'Automatic DM Control',
    'productpage.usp.3.desc': 'The automatic dry matter control reacts to changes in feed volume and consistency. Increases process reliability and enables constant operating conditions.',
    'productpage.usp.4.title': 'Fully Automatic Washing System',
    'productpage.usp.4.desc': '360° spray nozzles prevent buildup and blockages on the screen baskets. Operates in automatic intervals or by manual activation.',
    'productpage.voreindicker.title': 'Pre-Thickener',
    'productpage.voreindicker.desc': 'More information about our Pre-Thickener will follow shortly. Contact us for details.',
    'productpage.voreindicker.tagline': 'Coming soon',
    'productpage.voreindicker.intro': 'Our new Pre-Thickener extends the Filter Press Screw family. Technical data and datasheets will follow shortly.',
    'productpage.comingSoon': 'Coming Soon',
    'productpage.circulyizer.title': 'Circulyzer',
    'productpage.circulyizer.badge': 'Powered by Ecotexteria',
    'productpage.circulyizer.desc': 'Compact separation unit for wet density separation and washing of various residues and waste mixtures.',
    'productpage.circulyizer.tagline': 'Wet Density Separation',
    'productpage.circulyizer.intro': 'The Circulyzer separation unit is a compact system for wet density separation and washing of various residues and waste mixtures. The fully automated module in container design is particularly suitable for the processing of plastic/plastic, plastic/metal and plastic/paper mixtures. In addition to separation, the treated materials can also be washed.',
    'productpage.circulyizer.features.title': 'Features',
    'productpage.circulyizer.features': 'Float-sink separation in a centrifugal field – purely cylindrical cyclone (tube)|No rotating parts in the separation unit|Separation medium vortex (e.g. water) built up solely by flow|Direct feed of input material via patented dosing system – no dispersion required|Increased residence times at moderate flow velocities|Reduced wear and low feed pressure required (0.3 – 0.5 bar)|Simplified spare-parts handling through standardized components|Separation efficiency can be adjusted quickly (3–4 parameters depending on model)',
    'productpage.circulyizer.efficiency.title': 'Separation Efficiency',
    'productpage.circulyizer.efficiency.1.label': 'Rigid plastics',
    'productpage.circulyizer.efficiency.1.value': '> 99 %',
    'productpage.circulyizer.efficiency.1.desc': 'product purity achievable',
    'productpage.circulyizer.efficiency.2.label': 'Films / fibers',
    'productpage.circulyizer.efficiency.2.value': '> 95 %',
    'productpage.circulyizer.efficiency.2.desc': 'product purity achievable',
    'productpage.circulyizer.efficiency.3.label': 'Recovery rate',
    'productpage.circulyizer.efficiency.3.value': '> 98 %',
    'productpage.circulyizer.efficiency.3.desc': 'for both fractions achievable',
    'productpage.circulyizer.applications.ind.title': 'Industrial Applications',
    'productpage.circulyizer.applications.ind.items': 'Separation and washing of rigid plastics (PET, HDPE, engineering plastics)|Separation and washing of flexible plastics (films)|Washing of plastic and metal shavings|Separation of metallic "contaminants"|Separation of plastic/paper and plastic/metal mixtures|Pre-separation of heavy fractions|Dispersion of particles / fibers',
    'productpage.circulyizer.applications.agr.title': 'Agriculture / Food Industry Applications',
    'productpage.circulyizer.applications.agr.items': 'Washing and separation of freshly harvested vegetables, fruit, etc.|Gentle washing|Mixing reactor for solid-liquid or liquid-liquid processes',
    'productpage.circulyizer.benefits.title': 'Your Benefits',
    'productpage.circulyizer.benefits.items': 'Smaller footprint (only 6–8 m²), higher throughput (up to 9 t/h) and cleaner separation (up to 99.5 % purity) – that is efficiency.|Low pressure level (0.3 – 0.5 bar) enables low specific energy demand of 5 – 10 kWh/t input.|Instead of moving parts, we rotate water – minimizing maintenance and downtime.|Quickly adaptable process & design with standardized components simplify integration.|Focus on what matters: we monitor and control our plants purposefully (viewing windows, transparent sections …) – for easy and intuitive operation.',
    'productpage.circulyizer.options.title': 'Options',
    'productpage.circulyizer.options.items': 'Extended sensor package for monitoring and operator convenience (redundancy, camera monitoring, etc.)|Automatic adjustment of tilt angle and insertion depth of the dosing spiral|High-performance control with removable touchscreen, browser connection, performance measurement and self-cleaning mode|Control module for feeding with integrated overflow protection|Steel frame to customer specification|Integration / monitoring of process water tank|Process water tank incl. pre-filtration via vibrating screen|Further customer-specific options on request',
    'productpage.circulyizer.sizes.title': 'Three Sizes',
    'productpage.circulyizer.sizes.desc': 'The Circulyzer is available in three sizes – tailored to throughput and application. Detailed technical data will follow shortly in the datasheet.',
    'productpage.circulyizer.details.title': 'Construction & Operation',
    'productpage.circulyizer.details': 'For efficient separation, the materials must be previously shredded to < 10 – 40 mm. Integration into a stable frame construction makes handling, transport and installation in new and existing recycling plants easier.|In the simplest case, water is used as the separation medium for density separation. Depending on requirements, salt solutions (brines), slurries or water-surfactant mixtures can also be used.|The frame is made of coated black steel and the parts in contact with the medium are made of stainless steel (V4A, 1.4571 or similar).',
    'productpage.inquiry': 'Send Inquiry',
    'productpage.new': 'New',
    'productpage.flagship': 'Flagship',
    'productpage.compact': 'Compact',
    'productpage.options': 'Options',
    'productpage.features': 'Features',
    'productpage.cta.title': 'Looking for Individual Consultation?',
    'productpage.cta.desc': 'Our sales team is available for personalized advice.',
    'productpage.cta.find': 'Find a Sales Partner',
    'productpage.cta.contact': 'Contact Us',

    // Ersatzteile Page
    'ersatzteile.hero.badge': 'Our Know-How is Your Strength',
    'ersatzteile.hero.title': 'Spare Parts in OEM Quality – for Maximum Machine Performance',
    'ersatzteile.hero.desc': 'Ecotech Styria spare parts stand for precision manufacturing, high durability and reliable availability. So your plant runs economically in the long term – with minimal operating costs and maximum process reliability.',
    'ersatzteile.hero.cta': 'Contact Us',
    'ersatzteile.hero.cta2': 'View Services',
    'ersatzteile.facts.title': 'Key Facts',
    'ersatzteile.facts.1.title': 'Precise & Reliable',
    'ersatzteile.facts.1.desc': 'Original parts to OE standard',
    'ersatzteile.facts.2.title': 'High Durability',
    'ersatzteile.facts.2.desc': 'Material & manufacturing for the application',
    'ersatzteile.facts.3.title': 'Fast Identification',
    'ersatzteile.facts.3.desc': 'Technical advice from spare parts experts',
    'ersatzteile.facts.4.title': 'Screw Reconditioning',
    'ersatzteile.facts.4.desc': 'Reconditioning & hard-facing for a "second life"',
    'ersatzteile.beratung.title': 'Expert Advice That Makes the Difference',
    'ersatzteile.beratung.desc': 'Our spare parts experts support you in identifying the right spare or wear part. With professional technical advice, we ensure you receive the right solution quickly and reliably.',
    'ersatzteile.beratung.1.title': 'Part Identification Support',
    'ersatzteile.beratung.1.desc': 'Reliable, fast and practical',
    'ersatzteile.beratung.2.title': 'Clear Specifications',
    'ersatzteile.beratung.2.desc': 'For smooth ordering & short downtimes',
    'ersatzteile.preis.badge': 'Your Benefits',
    'ersatzteile.preis.title': 'Best Price-Performance Ratio',
    'ersatzteile.preis.desc': 'The efficiency of your plant is largely determined by the quality of the spare parts used. Whether screen basket or press screw – original Ecotech Styria spare parts deliver sustainable advantages in operation.',
    'ersatzteile.preis.1.title': 'Longer Service Life',
    'ersatzteile.preis.1.desc': 'Significantly higher durability compared to aftermarket parts',
    'ersatzteile.preis.2.title': 'Less Maintenance',
    'ersatzteile.preis.2.desc': 'Reduced downtime and lower maintenance costs',
    'ersatzteile.preis.3.title': 'Higher Machine Availability',
    'ersatzteile.preis.3.desc': 'Maximum performance at minimal operating costs',
    'ersatzteile.schnecken.badge': 'Service',
    'ersatzteile.schnecken.title': 'Screw Reconditioning – Quality at the Core of the Separator',
    'ersatzteile.schnecken.desc1': 'Screws are the central functional elements in separators – their quality is crucial for performance, service life and economic efficiency of the entire machine. Precisely maintained tolerances, process-reliable geometry and professional hard-facing with suitable methods and materials are essential for maximum wear resistance.',
    'ersatzteile.schnecken.desc2': 'Ecotech Styria offers professional reconditioning of your press screw. Through targeted repair, geometry adjustment and renewed wear coating, we give your screw a second life – economically, sustainably and in proven Ecotech Styria quality. Ecotech Styria also offers replacement screws for third-party machines – we are happy to handle your inquiry.',
    'ersatzteile.schnecken.1': 'Precise Tolerances — For stable processes and reproducible performance',
    'ersatzteile.schnecken.2': 'Hard-facing with Suitable Methods — Material & method for high wear resistance',
    'ersatzteile.schnecken.3': '"Second Life" for Your Press Screw — Professional reconditioning instead of costly replacement',
    'ersatzteile.oem.title': 'OEM Quality Over the Entire Machine Lifetime',
    'ersatzteile.oem.desc': 'Our spare and wear parts are developed and manufactured together with the original equipment. They are 100% precisely fitting, operationally safe and meet the same high quality standards as the original equipment.',
    'ersatzteile.tech.title': 'Always State of the Art',
    'ersatzteile.tech.desc': 'The continuous development of our products is part of our identity. This know-how naturally flows into our spare and wear parts – for future-proof solutions and consistently high plant performance.',
    'ersatzteile.contact.title': 'Quick to the Right Part – with Our Service',
    'ersatzteile.contact.desc': 'Send us your machine or part information – we support you with identification and create a suitable offer. Including screw reconditioning on request.',
    'ersatzteile.contact.cta': 'Send Email',
    'ersatzteile.contact.box.title': 'Your Contact for Spare Parts',

    // Service Page
    'service.hero.badge': 'On-Site Service · Plannable · Fast',
    'service.hero.title': 'Professional Maintenance with Ecotech Styria',
    'service.hero.desc': 'Regular maintenance reduces unplanned downtimes, preserves machine value and prevents consequential damage. Our service technicians support you efficiently and practically – directly at your site.',
    'service.hero.cta': 'Contact Service',
    'service.facts.title': 'Key Facts',
    'service.facts.1': 'On-site service with modern equipped service vehicles',
    'service.facts.2': 'Experienced and trained service technicians',
    'service.facts.3': 'Maintenance & servicing – plannable and documented',
    'service.facts.4': 'Option: turnkey installation & commissioning',
    'service.regular.title': 'Regular Service – Less Downtime, More Reliability',
    'service.regular.desc': 'Regularly maintained machines operate more stably, efficiently and cause fewer unplanned failures. At the same time, machine value is preserved long-term.',
    'service.regular.1': 'Minimize unplanned downtimes',
    'service.regular.2': 'Preserve machine value long-term',
    'service.regular.3': 'Reduce internal maintenance effort',
    'service.regular.4': 'Ensure calculable, transparent service costs',
    'service.install.title': 'Turnkey Installation & Commissioning',
    'service.install.desc': 'On request, we handle installation and commissioning of your new machine or plant – including training for efficient and safe operation.',
    'service.install.1': 'Professional assembly and clean integration into the process',
    'service.install.2': 'Commissioning & functional testing to defined standards',
    'service.install.3': 'Training of operating personnel for safe, efficient operation',
    'service.install.cta': 'Inquire Now',

    // Sales Page
    'sales.partner.label': 'Partner Network',
    'sales.partner.country.title': 'Choose Country',
    'sales.partner.country.all': 'All Countries',
    'sales.partner.empty.title': 'No sales partner in this country',
    'sales.partner.empty.desc': 'We currently do not have a sales partner in this region. Please reach out directly to our headquarters — we will support you personally.',
    'sales.partner.empty.cta': 'Contact us directly',
    'sales.partner.notfound.title': 'Haven\'t found a suitable sales partner?',
    'sales.partner.notfound.desc': 'Reach out directly to our headquarters — we are happy to help.',
    'sales.partner.notfound.cta': 'Get in touch',
    'sales.partner.become.title': 'Want to become our sales partner?',
    'sales.partner.become.desc': 'Become part of our distribution network and benefit from our expertise in separation technology.',
    'sales.partner.become.cta': 'Become a partner',
    'sales.partner.contact': 'Sales Contact:',
    'sales.form.company': 'Company',
    'sales.form.phone': 'Phone',
    'sales.form.placeholder': 'Tell us about your company and your region...',
    'sales.service.support': 'Support',
    'sales.service.items': 'Maintenance|Regular inspection and maintenance of your systems|Repair|Fast and reliable repair services|Technical Consulting|Expert knowledge for your separation processes|Commissioning|Professional installation and training',

    // Integration Page
    'integration.hero.title': 'System Integration – Installation and Commissioning',
    'integration.hero.subtitle': 'Everything from one hand – from idea to implementation.',

    'integration.overview.badge': 'Installation & Commissioning',
    'integration.overview.title': 'Everything from one hand – from idea to implementation',
    'integration.overview.p1': 'Ecotech Styria is a holistic partner for your plant. On request, we plan the machine integration into your installation and handle installation and commissioning as well — coordinated, efficient, and focused on economics.',
    'integration.overview.p2.bold': 'You focus on your business',
    'integration.overview.p2.rest': ' — Ecotech Styria takes care of optimizing your plant: coordinated interfaces, clean ramp-up and a stable processing flow from day one.',

    'integration.priorities.title': 'Priorities',
    'integration.priorities.intro': 'What we consistently optimize for during installation & commissioning:',
    'integration.priorities.1.title': 'High Plant Availability',
    'integration.priorities.1.desc': 'robust build & clean ramp-up',
    'integration.priorities.2.title': 'Lowest Processing Costs',
    'integration.priorities.2.desc': 'minimal energy & wear costs',
    'integration.priorities.3.title': 'Maintenance-friendly Design',
    'integration.priorities.3.desc': 'accessible components & service focus',
    'integration.priorities.4.title': 'Process Stability',
    'integration.priorities.4.desc': 'clean integration & reliable handover',

    'integration.leistung.title': 'Our Service – from planning to ramp-up',
    'integration.leistung.intro': 'We take over the complete machine integration and perform installation and commissioning in a structured way. Components and process steps work together — optimized for material flow, throughput and economics.',
    'integration.leistung.1.title': 'Integration Planning',
    'integration.leistung.1.desc': 'Interfaces, layout planning, media & peripherals — cleanly defined.',
    'integration.leistung.2.title': 'Installation & Assembly Coordination',
    'integration.leistung.2.desc': 'On schedule, safety-compliant and with a clear responsibility model.',
    'integration.leistung.3.title': 'Commissioning & Process Ramp-up',
    'integration.leistung.3.desc': 'Parameterization, function checks and stable processing from day one.',
    'integration.leistung.4.title': 'Handover & Optimization',
    'integration.leistung.4.desc': 'Documentation, training and fine-tuning for maximum economics.',

    'integration.partner.title': 'Service Package via Partner Network',
    'integration.partner.intro': 'Through its partners, Ecotech Styria can offer all required services — aligned, coordinated and with a single point of contact.',
    'integration.partner.1.title': 'Steel Construction',
    'integration.partner.1.desc': 'Structural design, platforms, frames, protective and service access.',
    'integration.partner.2.title': 'Control System Development',
    'integration.partner.2.desc': 'Automation, visualization, interfaces & safety concept.',
    'integration.partner.3.title': 'Assembly',
    'integration.partner.3.desc': 'Mechanics, piping, media connections — cleanly documented.',
    'integration.partner.4.title': 'Commissioning',
    'integration.partner.4.desc': 'Acceptance tests, trial runs, parameter setups and process stabilization.',
    'integration.partner.vorteil.label': 'Your Benefit:',
    'integration.partner.vorteil.text': 'A clear project flow with defined milestones — from integration to a stable running plant.',

    'integration.cta.title': 'Want to optimize your plant, buy it turnkey, and get it up and running quickly?',
    'integration.cta.desc': 'We support you from planning to ramp-up — aligned with your material stream and profitability goals.',
    'integration.cta.button': 'Get in touch',

    'integration.kontakt.title': 'Contact',
    'integration.kontakt.text': 'Send us your key data (material, throughput, existing situation, targets) — we will respond with a clear integration and commissioning plan.',

    // Agriculture Page
    'agriculture.title': 'Agriculture',
    'agriculture.subtitle': 'Efficient separation technology for livestock manure and fermentation residues from biogas plants.',
    'agriculture.intro.title': 'Customized Solutions for',
    'agriculture.intro.highlight': 'Agriculture',
    'agriculture.intro.desc': 'In modern agriculture, efficient management of nutrients and waste products is crucial for productivity and sustainability. Our EcoTech filter screw presses offer proven, robust and highly efficient solutions for separating solid and liquid components.',
    'agriculture.manure.title': 'Livestock Manure',
    'agriculture.manure.desc': 'The separation of cattle or pig manure significantly reduces the storage volume of the liquid phase. The recovered solid is excellent as fertilizer, while the liquid phase can be more easily applied to fields.',
    'agriculture.manure.points': 'Volume reduction of up to 30%|Easier application of the thin phase|Odor reduction|Solids usable as high-quality compost or bedding',
    'agriculture.biogas.title': 'Fermentation Residues from Biogas Plants',
    'agriculture.biogas.desc': 'Biogas plants benefit enormously from efficient separation of digestate. This improves nutrient logistics, reduces transport costs and optimizes operations.',
    'agriculture.biogas.points': 'Optimization of nutrient logistics|Reduction of transport and storage costs|More homogeneous liquid phase for better handling|Marketable solid fertilizer',
    'agriculture.findProduct': 'Find the Right Product',
    'agriculture.cta.title': 'Ready for Next-Generation Separation?',
    'agriculture.cta.desc': 'Contact us for a free technical consultation and find out how our filter screw presses can optimize your operations.',
    'agriculture.cta.button': 'Schedule a Consultation',

    // Applications Page
    'applications.findProduct': 'Find the Right Product',
    'applications.page.subtitle': 'Discover the diverse applications of our separation technology – from agriculture to the food industry.',
    'productpage.bg2.options': 'Automatic washing device for filter and press screen|Sensor packages for monitoring|ECO control with manual regulation|PRO control with HMI panel and ProfiNET|Inlet piping with telescopic pipe|Control module for feed pumps|Additional base frame for higher working height|Customer-specific options as needed',
    'productpage.bgi400.features': 'Compact design – ideal for smaller process streams up to approx. 20 m³/h|Optimal solution for agricultural applications and farming operations|High DM content in solids – suitable for premium bedding|Simple plug & play solution with built-in frequency converter|Stainless steel design (1.4301 / AISI 304)|Stainless steel screw with hard-facing|Stainless steel slot screens|Inlet pressure up to 1.2 bar|Inlet piping with telescopic pipe and overflow pipe',
    'productpage.subtitle': 'Discover our innovative separation solutions for maximum efficiency and longevity.',

    // News Page
    'newspage.title': 'News & Media',
    'newspage.hero.subtitle': 'Stay up to date with the latest news, success stories, and developments at EcoTech Styria.',
    'newspage.sections.news': 'News & Success Stories',
    'newspage.sections.events': 'Trade Fairs & Events',
    'newspage.downloads.title': 'Downloads',
    'newspage.downloads.desc': 'Images, Renderings, Brochures',
    'newspage.downloads.text': 'Download our product brochures, technical data sheets, and images.',
    'newspage.download.brochureBg2': 'Product Brochure BGII-800',
    'newspage.download.brochureBgi400': 'Product Brochure BGI-400',
    'newspage.download.datasheetBg2': 'Technical Data Sheet BGII-800',
    'newspage.download.datasheetBgi400': 'Technical Data Sheet BGI-400',
    'newspage.download.imagesBg2': 'Product Images BGII-800',
    'newspage.download.imagesBgi400': 'Product Images BGI-400',
    'newspage.download.recyclingSheet': 'Plastic Recycling Application Sheet',
    'newspage.readMore': 'Read more',
    'newspage.showLess': 'Show less',
    'newspage.eventReadMore': 'Learn more',

    // Home Page section labels
    'home.sections.applications': 'Areas',
    'home.sections.products': 'Products',
    'home.sections.benefits': 'Benefits',
    'home.sections.news': 'Latest',

    // About Page section labels
    'aboutpage.team.label': 'Team',
    'aboutpage.contact.label': 'Contact',
    'aboutpage.location.label': 'Location',
    'aboutpage.contact.formSuccess': 'Thank you for your message! We will get back to you soon.',

    // Sales Page – Spare Parts preview
    'salespage.spareparts.label': 'Spare Parts',
    'salespage.spareparts.title': 'Original Spare Parts — for Maximum Machine Performance',
    'salespage.spareparts.desc': 'Ecotech Styria spare parts stand for precision-fit manufacturing, long service life, and reliable availability — keeping your plant economically viable with minimal operating costs and maximum process safety.',
    'salespage.spareparts.highlight1': 'OEM quality — precision-fit, durable, operationally safe',
    'salespage.spareparts.highlight2': 'Screw refurbishment — a "second life" for your press screw',
    'salespage.spareparts.highlight3': 'Expert advice on identification & ordering',
    'salespage.spareparts.highlight4': 'Short delivery times directly from the manufacturer',
    'salespage.spareparts.cta': 'View all services',
    'salespage.schnecken.title': 'Screw Refurbishment — Quality at the Core of the Separator',
    'salespage.schnecken.desc': 'Screws are the central functional elements in separators. Ecotech Styria offers professional refurbishment of your press screw: targeted repair, geometry adjustment, and renewed wear coating — for a second life of your screw.',
    'salespage.schnecken.cta': 'More about screw refurbishment',

    // Sales Page – Service preview
    'salespage.service.label': 'Service & Commissioning',
    'salespage.service.title': 'Professional Maintenance with Ecotech Styria',
    'salespage.service.desc': 'Regularly serviced machines are more reliable and have fewer unplanned outages. Fast, expert support from our experienced service technicians — directly at your facility.',
    'salespage.service.benefit1': 'Minimize unplanned downtime',
    'salespage.service.benefit2': 'Preserve machine value long-term',
    'salespage.service.benefit3': 'Reduce in-house maintenance effort',
    'salespage.service.benefit4': 'Predictable, transparent service costs',
    'salespage.service.cta': 'View service offerings',
    'salespage.install.title': 'Turnkey Installation & Commissioning',
    'salespage.install.desc': 'On request, we handle installation and commissioning of your new machine or plant — including training for efficient and safe operation.',
    'salespage.install.cta': 'More about service',

    // Products Page – BGI-400 technical data
    'productpage.bgi400.tech.title': 'Technical Data',
    'productpage.bgi400.tech.drive': 'Drive power',
    'productpage.bgi400.tech.drive.val': '2.2 - 3.0 kW\n(3.0 - 4.0 HP)',
    'productpage.bgi400.tech.throughput': 'Throughput',
    'productpage.bgi400.tech.throughput.val': 'up to 20 m³/h\n(up to 90 gpm)',
    'productpage.bgi400.tech.gap': 'Screen slot',
    'productpage.bgi400.tech.gap.val': '100 - 1000 µm',
    'productpage.bgi400.tech.dry_org': 'Dry matter organic fibers',
    'productpage.bgi400.tech.dry_org.val': 'up to 42%',
    'productpage.bgi400.tech.dry_inorg': 'Dry matter inorganic fibers',
    'productpage.bgi400.tech.dry_inorg.val': 'up to 85%',
    'productpage.bgi400.tech.pressure': 'Feed pressure',
    'productpage.bgi400.tech.pressure.val': 'up to 1.2 bar',
    'productpage.bgi400.tech.disclaimer': 'Performance data depends on the consistency and viscosity of the medium to be separated.',

    // BGI-400 Plug & Play (new 2026-04-20)
    'productpage.bgi400pnp.title': 'BGI-400 Plug & Play',
    'productpage.bgi400pnp.badge': 'Mobile',
    'productpage.bgi400pnp.desc': 'The mobile Plug & Play variant of our compact filter screw press BGI-400 — the same proven technology in a prefabricated, location-flexible unit. Simply connect, set up, and start operation.',
    'productpage.bgi400pnp.features': 'Mobile unit — ready to use without a foundation|Automatic pressure monitoring|Galvanized steel frame — durable and weather-resistant|Integrated rotary lobe pump',

    // Header / Footer extras
    'nav.languageLabel': 'Language:',
    'footer.social': 'Social Media',
    'footer.links': 'Links',
    'footer.navigation': 'Navigation',
    'footer.rights': 'All rights reserved.',

    // Legal Pages
    'legal.terms.title': 'Terms & Conditions',
    'legal.terms.label': 'Legal',
    'legal.terms.1.title': '1. Scope',
    'legal.terms.1.body': 'These General Terms and Conditions apply to all deliveries and services provided by EcoTech Styria GmbH to its customers.',
    'legal.terms.2.title': '2. Conclusion of Contract',
    'legal.terms.2.body': 'A contract is concluded by written order confirmation or by execution of the order.',
    'legal.terms.3.title': '3. Prices and Payment Terms',
    'legal.terms.3.body': 'All prices are in Euro plus statutory VAT. Payments are due within 14 days of invoice date.',
    'legal.terms.4.title': '4. Delivery',
    'legal.terms.4.body': 'Delivery dates are stated to the best of our knowledge but are non-binding unless expressly agreed as binding.',
    'legal.terms.5.title': '5. Warranty',
    'legal.terms.5.body': 'The warranty period is 12 months from handover of the goods. No warranty is assumed for used goods.',
    'legal.terms.6.title': '6. Liability',
    'legal.terms.6.body': 'Liability for slight negligence is excluded, provided no essential contractual obligations are breached.',
    'legal.terms.7.title': '7. Reservation of Title',
    'legal.terms.7.body': 'The delivered goods remain the property of EcoTech Styria GmbH until payment in full.',
    'legal.terms.8.title': '8. Place of Jurisdiction',
    'legal.terms.8.body': 'Place of jurisdiction is Graz. Austrian law applies, excluding the UN Convention on Contracts for the International Sale of Goods.',

    'legal.privacy.title': 'Privacy Policy',
    'legal.privacy.label': 'Privacy',
    'legal.privacy.1.title': 'Data Controller',
    'legal.privacy.1.body': 'EcoTech Styria GmbH\nJudenburgerstraße 176\nA-8580 Köflach, Austria\nEmail: office@ecotechstyria.com',
    'legal.privacy.2.title': 'Collection and Processing of Personal Data',
    'legal.privacy.2.body': 'We collect and process personal data only insofar as it is necessary to provide our services. This includes contact data for inquiries and orders.',
    'legal.privacy.3.title': 'Purpose of Data Processing',
    'legal.privacy.3.body': 'The collected data is used to handle inquiries, process orders, and communicate with our customers and partners.',
    'legal.privacy.4.title': 'Legal Basis',
    'legal.privacy.4.body': 'Processing is carried out on the basis of Art. 6 GDPR (contract performance, legitimate interest, consent).',
    'legal.privacy.5.title': 'Data Security',
    'legal.privacy.5.body': 'We use technical and organizational measures to protect your data against manipulation, loss, destruction, or unauthorized access.',
    'legal.privacy.6.title': 'Your Rights',
    'legal.privacy.6.body': 'You have the right to access, rectification, erasure, restriction of processing, data portability, and objection. Contact us at office@ecotechstyria.com.',
    'legal.privacy.7.title': 'Cookies',
    'legal.privacy.7.body': 'Our website uses cookies exclusively for technical functionality. No tracking cookies are used.',

    'legal.imprint.title': 'Legal Notice',
    'legal.imprint.label': 'Legal',
    'legal.imprint.company': 'Company Information',
    'legal.imprint.legalInfo': 'Legal Information',
    'legal.imprint.management': 'Management',
    'legal.imprint.uid': 'VAT Number',
    'legal.imprint.fbn': 'Commercial Register Number',
    'legal.imprint.fbg': 'Commercial Register Court',
    'legal.imprint.fbg.val': 'Regional Court for Civil Matters Graz',
    'legal.imprint.member': 'Member of',
    'legal.imprint.member.val': 'WKO Styria',
    'legal.imprint.authority': 'Authority pursuant to ECG',
    'legal.imprint.authority.val': 'District Authority Voitsberg',
    'legal.imprint.profession': 'Professional Title',
    'legal.imprint.profession.val': 'Mechatronics Engineer for Mechanical and Manufacturing Engineering',

    'legal.dealers.title': 'Our Dealers',
    'legal.dealers.label': 'Sales',
    'legal.dealers.intro': 'Our authorized sales partners are available to provide local consultation, sales, and service.',
    'legal.dealers.becomeQuestion': 'Would you also like to become a sales partner?',
    'legal.dealers.learnMore': 'Learn more',
    'legal.dealers.country.slovenia': 'Slovenia',
    'legal.dealers.country.austria': 'Austria',
    'legal.dealers.country.usa': 'USA',

    // Contact Form
    'form.name': 'Name',
    'form.email': 'Email',
    'form.subject': 'Subject',
    'form.message': 'Message',
    'form.submit': 'Submit',
    'form.sendApplication': 'Send Application',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('de');

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    document.documentElement.lang = lang;
  }, []);

  const t = useCallback((key: string): string => {
    const translation = translations[language][key as keyof typeof translations.de];
    return translation || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
