import React, { createContext, useContext, useState, useCallback } from 'react';

type Language = 'de' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  de: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'Über uns',
    'nav.sales': 'Vertrieb & Aftersales',
    'nav.applications': 'Anwendungen',
    'nav.products': 'Produkte',
    'nav.integration': 'Systemintegration',
    'nav.news': 'News & Medien',

    // Footer
    'footer.terms': 'AGB',
    'footer.privacy': 'Datenschutz',
    'footer.legal': 'Impressum',
    'footer.dealers': 'Händler',

    // Hero
    'hero.headline': 'Next Level Separation',
    'hero.subheadline': 'Innovative Lösungen zur Fest-Flüssig-Trennung',
    'hero.cta': 'Mehr erfahren',

    // About Section
    'about.title': 'Über uns',
    'about.description': 'Mit mehr als 15 Jahren Erfahrung in der Entwicklung und technischen Anwendungen im Maschinenbau und Anlagenaufbau mit einem Schwerpunkt Separations- und Umwelttechnik.',
    'about.link': 'Zur Unternehmensseite',

    // Applications Section
    'applications.title': 'Anwendungen',
    'applications.learnMore': 'Mehr erfahren',
    'applications.agriculture.title': 'Landwirtschaft',
    'applications.agriculture.desc': 'Gülle von Nutztieren, Gärreste aus Biogasanlagen',
    'applications.bedding.title': 'Einstreuerzeugung',
    'applications.bedding.desc': 'Separation zur Einstreu- und Düngerproduktion',
    'applications.biogas.title': 'Biogas',
    'applications.biogas.desc': 'Gärreste aus Biogasanlagen',
    'applications.recycling.title': 'Kunststoff Recycling',
    'applications.recycling.desc': 'Abwasser aus Depackinganlagen und Kunststoffrecyclinganlagen',
    'applications.municipal.title': 'Kommunalwirtschaft',
    'applications.municipal.desc': 'Primär- und Sekundärschlämme aus Kläranlagen',
    'applications.paper.title': 'Papierindustrie',
    'applications.paper.desc': 'Rejekte und Sekundärschlämme',
    'applications.mdf.title': 'Prozessmedien und Abwässer',
    'applications.mdf.desc': 'Produktionsabwässer und Prozessmedien aus industriellen Anlagen',
    'applications.food.title': 'Nebenprodukte und Abwässer',
    'applications.food.desc': 'Schlachthausabwasser, Waschwasser, Brauereiabfälle und industrielle Nebenprodukte',

    // Products Section
    'products.title': 'Produkte',
    'products.viewDetails': 'Zu den Details',
    'products.bg2.name': 'Filterschneckenpresse BGII-800',
    'products.bg2.feature1': 'Bis zu 75m³/h Durchsatz',
    'products.bg2.feature2': 'Bis zu 75% TS-Gehalt',
    'products.bg2.feature3': 'Edelstahlkonstruktion',
    'products.bgi400.name': 'Filterschneckenpresse BGI-400',
    'products.bgi400.feature1': 'Bis zu 20m³/h Durchsatz',
    'products.bgi400.feature2': 'Kompakte Bauweise',
    'products.bgi400.feature3': 'Plug & Play Lösung',

    // Why Separation Section
    'why.title': 'Warum separieren?',
    'why.point1': 'Verringerung von Lagervolumen',
    'why.point2': 'Wiederverwendung der Feststoffe',
    'why.point3': 'Reduktion der Entsorgungskosten',
    'why.point4': 'Wiederverwendung der Flüssigphase als Prozesswasser',
    'why.point5': 'Reduktion der Energiekosten',
    'why.point6': 'Reduktion von Prozesskosten',
    'why.point7': 'Einhaltung von Umweltvorgaben',
    'why.point8': 'Verbesserte Eigenschaften der separierten Phasen',

    // Optimization Section
    'optimization.label': 'Prozessoptimierung',
    'optimization.title': 'Messbar effizienter',
    'optimization.text': 'Wir machen Separationsprozesse messbar effizienter. Durch intelligente Optimierungen reduzieren wir Energieverbrauch, Verschleiß und Betriebskosten – und steigern gleichzeitig die Leistungsfähigkeit bestehender Systeme. Dabei bleibt es nicht bei der Analyse: Wir setzen Verbesserungen gemeinsam mit unseren Kunden konsequent um und schaffen so nachhaltigen Mehrwert.',

    // News Section
    'news.title': 'News & Erfolgsgeschichten',
    'news.readMore': 'Weiterlesen',

    // About Page
    'aboutpage.intro.title': 'Wer sind wir?',
    'aboutpage.vision.title': 'Vision & Mission',
    'aboutpage.vision.label': 'Vision:',
    'aboutpage.vision.text': 'Separationstechnik auf den nächsten Level zu bringen',
    'aboutpage.slogan.label': 'Slogan:',
    'aboutpage.slogan.text': 'Next Level Separation',
    'aboutpage.mission.label': 'Mission:',
    'aboutpage.mission.text': 'Wir machen Separationsprozesse messbar effizienter. Durch intelligente Optimierungen reduzieren wir Energieverbrauch, Verschleiß und Betriebskosten – und steigern gleichzeitig die Leistungsfähigkeit bestehender Systeme. Dabei bleibt es nicht bei der Analyse: Wir setzen Verbesserungen gemeinsam mit unseren Kunden konsequent um und schaffen so nachhaltigen Mehrwert.',
    'aboutpage.team.title': 'Unser Team',
    'aboutpage.team.ceo.name': 'Heinz Leitner',
    'aboutpage.team.ceo.role': 'CEO',
    'aboutpage.team.ceo.bio': '>15 Jahre einschlägige Managementerfahrung im internationalen Umwelttechnikmaschinen- und Anlagenbau',
    'aboutpage.team.coo.name': 'Gernot Pauger',
    'aboutpage.team.coo.role': 'COO',
    'aboutpage.team.coo.bio': '>15 Jahre Erfahrung in der Entwicklung und Produktion von Sondermaschinen für Umwelt- und Landtechnik',
    'aboutpage.team.cto.name': 'Thomas Kampl',
    'aboutpage.team.cto.role': 'CTO',
    'aboutpage.team.cto.bio': '>15 Jahre Erfahrung als Anwendungsspezialist im Bereich von Separationstechnik für Fest-Flüssigtrennung',
    'aboutpage.team.cso.name': 'Günther Pirker',
    'aboutpage.team.cso.role': 'CSO',
    'aboutpage.team.cso.bio': '>15 Jahre Branchenerfahrung mit Schwerpunkt Produktion und internationalem Vertrieb von Land- und Umwelttechnikmaschinen',
    'aboutpage.team.description': 'Wir sind ein interdisziplinäres Team aus Ingenieuren, Anwendungsspezialisten und Branchenkennern, das eines verbindet: der Anspruch, technologisch führende Lösungen für die Separation von flüssigen und festen Stoffen zu entwickeln. Unser Ansatz ist systemorientiert und lösungsfokussiert. Wir analysieren etablierte Aufbereitungsprozesse ganzheitlich, entwickeln maßgeschneiderte Maschinen- und Anlagenkonzepte mit deutlich höherer Effizienz und setzen auf eine enge Zusammenarbeit mit unseren Kund:innen.',

    // Partner Section
    'aboutpage.partner.title': 'Ecotech Styria - Partner',
    'aboutpage.partner.exclusive': 'exklusiver Produktionspartner',
    'aboutpage.partner.ecotech.subtitle': 'Fest-Flüssig-Trennung',
    'aboutpage.partner.ecotech.bullet1': 'F&E',
    'aboutpage.partner.ecotech.bullet2': 'Produktmanagement',
    'aboutpage.partner.ecotech.bullet3': 'Vertrieb',
    'aboutpage.partner.ecotech.bullet4': 'Kundendienst',
    'aboutpage.partner.pauger.subtitle': 'Engineering & Produktion',
    'aboutpage.partner.pauger.bullet1': 'Engineering & Design',
    'aboutpage.partner.pauger.bullet2': 'Produktion von Maschinen und Komponenten',
    'aboutpage.partner.pauger.bullet3': 'Ersatzteillager',

    'aboutpage.contact.title': 'Kontakt',
    'aboutpage.location.title': 'Standort',
    'aboutpage.careers.title': 'Karriere – offene Stellen',
    'aboutpage.careers.text': 'Wir suchen talentierte und motivierte Fachkräfte. Bitte senden Sie Ihre Bewerbung an: office@ecotechstyria.com',

    // Sales Page
    'sales.findPartner.title': 'Vertriebspartner finden',
    'sales.findPartner.desc': 'Siehe Partner der TCS Umwelttechnik. Sie haben keinen passenden Vertriebspartner gefunden? Sie möchten Vertriebspartner werden?',
    'sales.becomePartner.title': 'Sie möchten unser Vertriebspartner werden?',
    'sales.spareparts.title': 'Ersatzteile',
    'sales.spareparts.desc': 'Wir bieten ein umfassendes Sortiment an Ersatzteilen für alle unsere Maschinen. Kontaktieren Sie uns für ein Angebot.',
    'sales.service.title': 'Service',
    'sales.service.desc': 'Unser erfahrenes Service-Team steht Ihnen bei Wartung, Reparatur und technischer Unterstützung zur Verfügung.',

    // Products Page
    'productpage.bg2.title': 'Filterschneckenpresse BGII-800',
    'productpage.bg2.desc': 'Die Filterschneckenpresse BGII-800 ist unsere Flaggschiff-Maschine für Hochleistungs-Separationen. Mit patentierter Geometrie und automatischer Wascheinrichtung bietet sie optimale Effizienz und minimalen Verschleiß.',

    // BG2 PDF Content
    'productpage.bg2.applications.ind.title': 'Anwendungen Industrie',
    'productpage.bg2.applications.ind.items': 'Kunststoffrecycling|Pulp & Paper|Schlachthofabwässer|Kommunale Abwässer|Lebensmittelverarbeitung',
    'productpage.bg2.applications.agr.title': 'Anwendungen Landwirtschaft',
    'productpage.bg2.applications.agr.items': 'Gülle von Nutztieren|Gärreste aus Biogasanlagen',
    'productpage.bg2.benefits.title': 'Vorteile',
    'productpage.bg2.benefits.items': 'Reduktion von Entsorgungskosten|Wiederverwendung der Feststoffe|Wiederverwendung der flüssigen Phase|Einfacheres Nährstoffmanagement|Höhere Prozesseffizienz',
    'productpage.bg2.features.title': 'Merkmale',
    'productpage.bg2.features.items': 'Edelstahl-Konstruktion|Geringer Spalt zwischen Sieb und Schnecke|Bis zu 0,5 bar Zulaufdruck|Geschlossenes System, automatische Wascheinrichtung|Steuerungen mit offener Schnittstelle (ProfiNet etc.) für einfache Einbindung|Verminderter Verschleiß und höherer Durchsatz durch patentierte Schneckengeometrie und Stützkonstruktion im Pressbereich|Vollautomatische Regelung des Trockensubstanz-Gehaltes im Feststoff|Überwachung des Betriebszustands (Variation im Zulauf, Leckagen, Drehmoment, Ölqualität etc.)|Höchst abrasionsbeständige Schneckenbeschichtung',
    'productpage.bg2.tech.title': 'Technische Daten',
    'productpage.bg2.tech.drive': 'Antrieb',
    'productpage.bg2.tech.drive.val': '5,5 - 11,0 kW',
    'productpage.bg2.tech.throughput': 'Durchsatz',
    'productpage.bg2.tech.throughput.val': 'bis zu 75m³/h',
    'productpage.bg2.tech.gap': 'Spaltweite',
    'productpage.bg2.tech.gap.val': '100 - 1000 µm',
    'productpage.bg2.tech.dry_org': 'Trockensubstanz Organische Fasern',
    'productpage.bg2.tech.dry_org.val': 'bis zu 40%',
    'productpage.bg2.tech.dry_inorg': 'Trockensubstanz Anorganische Fasern',
    'productpage.bg2.tech.dry_inorg.val': 'bis zu 75%',
    'productpage.bg2.tech.disclaimer': 'Die Leistungsdaten hängen von Zusammensetzung und Viskosität des Mediums ab.',
    'productpage.bgi400.title': 'Filterschneckenpresse BGI-400',
    'productpage.bgi400.desc': 'Die kompakte Filterschneckenpresse BGI-400 ist ideal für Agrar-Anwendungen. Mit ihrer Plug-and-Play-Lösung und hohem TS-Gehalt im Feststoff bietet sie eine kostengünstige Lösung für Gülleseparation und Einstreu-Produktion.',
    'productpage.bgi400.availability': 'Verfügbar ab Q4/25',

    // USP Section
    'productpage.usp.title': 'USP – Patentierte Technologie',
    'productpage.usp.1.title': 'Patentierte Filterschneckengeometrie',
    'productpage.usp.1.desc': 'Die patentierte Filterschneckengeometrie mit zusätzlichen Schneckenflügeln im Filterbereich sorgt für gesteigerten spezifischen Durchsatz und verringerten Verschleiß.',
    'productpage.usp.2.title': 'Patentiertes Stützgehäuse',
    'productpage.usp.2.desc': 'Das patentierte Stützgehäuse stützt den Presssieb und absorbiert den Berstdruck. Ermöglicht höheren Pressdruck und damit höheren TS-Gehalt im Feststoff bei reduziertem Verschleiß.',
    'productpage.usp.3.title': 'Automatische TS-Regelung',
    'productpage.usp.3.desc': 'Die automatische TS-Regelung reagiert auf Änderungen in Zulaufmenge und -konsistenz. Erhöht die Prozesssicherheit und ermöglicht konstanten Betriebszustand.',
    'productpage.usp.4.title': 'Vollautomatische Wascheinrichtung',
    'productpage.usp.4.desc': '360° Sprühdüsen verhindern Anhaftungen und Verstopfungen an den Siebkörben. Arbeitet in automatischen Intervallen oder bei händischer Betätigung.',
    'productpage.voreindicker.title': 'Voreindicker / Pre-Thickener',
    'productpage.voreindicker.desc': 'Weitere Informationen zu unserem Voreindicker folgen in Kürze. Kontaktieren Sie uns für Details.',
    'productpage.circulyizer.title': 'Circulyizer',
    'productpage.circulyizer.desc': 'Weitere Informationen zu unserem Circulyizer folgen in Kürze. Kontaktieren Sie uns für Details.',
    'productpage.inquiry': 'Anfrage stellen',
    'productpage.new': 'Neu',
    'productpage.flagship': 'Flaggschiff',
    'productpage.compact': 'Kompakt',
    'productpage.options': 'Optionen',
    'productpage.features': 'Merkmale',
    'productpage.cta.title': 'Individuelle Beratung gewünscht?',
    'productpage.cta.desc': 'Unser Vertriebsteam steht Ihnen für eine persönliche Beratung zur Verfügung.',
    'productpage.cta.find': 'Vertriebspartner finden',
    'productpage.cta.contact': 'Kontakt aufnehmen',

    // Ersatzteile Page
    'ersatzteile.hero.badge': 'Unser Know-how ist Ihre Stärke',
    'ersatzteile.hero.title': 'Ersatzteile in Erstausrüster-Qualität – für maximale Maschinenperformance',
    'ersatzteile.hero.desc': 'Ecotech Styria Ersatzteile stehen für passgenaue Fertigung, hohe Standzeiten und verlässliche Verfügbarkeit. Damit Ihre Anlage dauerhaft wirtschaftlich läuft – mit minimalen Betriebskosten und maximaler Prozesssicherheit.',
    'ersatzteile.hero.cta': 'Kontakt aufnehmen',
    'ersatzteile.hero.cta2': 'Leistungen ansehen',
    'ersatzteile.facts.title': 'Kurzfakten',
    'ersatzteile.facts.1.title': 'Passgenau & einsatzsicher',
    'ersatzteile.facts.1.desc': 'Originalteile nach OE-Standard',
    'ersatzteile.facts.2.title': 'Hohe Standzeiten',
    'ersatzteile.facts.2.desc': 'Material & Fertigung für den Einsatzzweck',
    'ersatzteile.facts.3.title': 'Schnelle Identifizierung',
    'ersatzteile.facts.3.desc': 'Technische Beratung durch Ersatzteilexperten',
    'ersatzteile.facts.4.title': 'Schneckenaufbereitung',
    'ersatzteile.facts.4.desc': 'Instandsetzung & Aufpanzerung für „zweites Leben"',
    'ersatzteile.beratung.title': 'Kompetente Beratung, die den Unterschied macht',
    'ersatzteile.beratung.desc': 'Unsere Ersatzteilexperten unterstützen Sie bei der Identifizierung des passenden Ersatz- oder Verschleißteils. Mit fundierter technischer Beratung sorgen wir dafür, dass Sie schnell und sicher die richtige Lösung erhalten – unkompliziert und zuverlässig.',
    'ersatzteile.beratung.1.title': 'Hilfestellung bei der Teilezuordnung',
    'ersatzteile.beratung.1.desc': 'Sicher, schnell und praxisnah',
    'ersatzteile.beratung.2.title': 'Klare Spezifikationen',
    'ersatzteile.beratung.2.desc': 'Für eine reibungslose Bestellung & kurze Stillstandszeiten',
    'ersatzteile.preis.badge': 'Ihre Vorteile',
    'ersatzteile.preis.title': 'Bestes Preis-Leistungs-Verhältnis',
    'ersatzteile.preis.desc': 'Die Wirtschaftlichkeit Ihrer Anlage wird maßgeblich durch die Qualität der eingesetzten Ersatzteile bestimmt. Ob Siebkorb oder Pressschnecke – originale Ecotech Styria Ersatzteile liefern nachhaltige Vorteile im Betrieb.',
    'ersatzteile.preis.1.title': 'Längere Lebensdauer',
    'ersatzteile.preis.1.desc': 'Im Vergleich zu Nachbauteilen deutlich höhere Standzeiten',
    'ersatzteile.preis.2.title': 'Weniger Wartungsaufwand',
    'ersatzteile.preis.2.desc': 'Reduzierte Stillstände und geringere Instandhaltungskosten',
    'ersatzteile.preis.3.title': 'Höhere Maschinenverfügbarkeit',
    'ersatzteile.preis.3.desc': 'Maximale Performance bei minimalen Betriebskosten',
    'ersatzteile.schnecken.badge': 'Service',
    'ersatzteile.schnecken.title': 'Aufbereitung von Schnecken – Qualität im Kern des Separators',
    'ersatzteile.schnecken.desc1': 'Schnecken sind die zentralen Funktionselemente in Separatoren – ihre Qualität ist entscheidend für Leistungsfähigkeit, Standzeit und Wirtschaftlichkeit der gesamten Maschine. Entscheidend sind dabei exakt eingehaltene Toleranzen, eine prozesssichere Geometrie sowie die fachgerechte Aufpanzerung mit geeigneten Verfahren und Werkstoffen für maximale Verschleißfestigkeit.',
    'ersatzteile.schnecken.desc2': 'Ecotech Styria bietet die professionelle Aufbereitung Ihrer Pressschnecke an. Durch gezielte Instandsetzung, Anpassung der Geometrie und erneute Verschleißbeschichtung verleihen wir Ihrer Schnecke ein zweites Leben – wirtschaftlich, nachhaltig und in bewährter Ecotech-Styria-Qualität.',
    'ersatzteile.schnecken.1': 'Präzise Toleranzen — Für stabile Prozesse und reproduzierbare Performance',
    'ersatzteile.schnecken.2': 'Aufpanzerung mit passenden Verfahren — Werkstoff & Methode für hohe Verschleißfestigkeit',
    'ersatzteile.schnecken.3': '„Zweites Leben" für Ihre Pressschnecke — Professionelle Instandsetzung statt teurer Neuanschaffung',
    'ersatzteile.oem.title': 'Erstausrüster-Qualität über die gesamte Maschinenlebensdauer',
    'ersatzteile.oem.desc': 'Unsere Ersatz- und Verschleißteile werden gemeinsam mit der Originalausrüstung entwickelt und gefertigt. Sie sind 100% passgenau, einsatzsicher und erfüllen dieselben hohen Qualitätsanforderungen wie die Erstausrüstung.',
    'ersatzteile.tech.title': 'Immer am aktuellen Stand der Technik',
    'ersatzteile.tech.desc': 'Die kontinuierliche Weiterentwicklung unserer Produkte ist Teil unseres Selbstverständnisses. Dieses Know-how fließt selbstverständlich auch in unsere Ersatz- und Verschleißteile ein – für zukunftssichere Lösungen und dauerhaft hohe Anlagenperformance.',
    'ersatzteile.contact.title': 'Schnell zum richtigen Teil – mit unserem Service',
    'ersatzteile.contact.desc': 'Senden Sie uns Ihre Maschinen- bzw. Teileinformationen – wir unterstützen Sie bei der Identifizierung und erstellen ein passendes Angebot. Auf Wunsch inkl. Schneckenaufbereitung.',
    'ersatzteile.contact.cta': 'E-Mail senden',
    'ersatzteile.contact.box.title': 'Ihr Kontakt für Ersatzteile',

    // Service Page
    'service.hero.badge': 'Vor-Ort-Service · Planbar · Schnell',
    'service.hero.title': 'Professionelle Wartung mit Ecotech Styria',
    'service.hero.desc': 'Regelmäßige Wartung reduziert ungeplante Stillstände, erhält den Maschinenwert und verhindert Folgeschäden. Unsere Servicetechniker unterstützen Sie effizient und praxisnah – direkt bei Ihnen im Betrieb.',
    'service.hero.cta': 'Service kontaktieren',
    'service.facts.title': 'Kurzfakten',
    'service.facts.1': 'Vor-Ort-Service mit modern ausgestatteten Servicefahrzeugen',
    'service.facts.2': 'Erfahrene und geschulte Servicetechniker',
    'service.facts.3': 'Wartung & Instandhaltung – planbar und dokumentiert',
    'service.facts.4': 'Option: schlüsselfertige Installation & Inbetriebnahme',
    'service.regular.title': 'Regelmäßiger Service – weniger Stillstand, mehr Sicherheit',
    'service.regular.desc': 'Regelmäßig gewartete Maschinen arbeiten stabiler, effizienter und verursachen weniger ungeplante Ausfälle. Gleichzeitig bleibt der Maschinenwert langfristig erhalten.',
    'service.regular.1': 'Ungeplante Ausfallzeiten minimieren',
    'service.regular.2': 'Maschinenwert langfristig erhalten',
    'service.regular.3': 'Internen Wartungsaufwand reduzieren',
    'service.regular.4': 'Kalkulierbare, transparente Servicekosten sicherstellen',
    'service.install.title': 'Schlüsselfertige Installation & Inbetriebnahme',
    'service.install.desc': 'Auf Wunsch übernehmen wir die Installation und Inbetriebnahme Ihrer neuen Maschine oder Anlage – inklusive Einschulung für effizientes und sicheres Arbeiten.',
    'service.install.1': 'Fachgerechte Montage und saubere Integration in den Prozess',
    'service.install.2': 'Inbetriebnahme & Funktionsprüfung nach definierten Standards',
    'service.install.3': 'Einschulung des Bedienpersonals für sicheren, effizienten Betrieb',
    'service.install.cta': 'Jetzt anfragen',

    // Sales Page
    'sales.partner.label': 'Partnerschaft',
    'sales.partner.desc': 'Sie haben keinen passenden Vertriebspartner gefunden? Werden Sie Teil unseres globalen Vertriebsnetzwerks und profitieren Sie von unserer Expertise in der Separationstechnologie.',
    'sales.partner.tcs': 'Siehe',
    'sales.partner.tcs.link': 'Partner der TCS Umwelttechnik',
    'sales.partner.find': 'Vertriebspartner finden',
    'sales.partner.notfound': 'Sie haben keinen passenden Vertriebspartner gefunden',
    'sales.partner.become': 'Sie möchten Vertriebspartner werden',
    'sales.partner.contact': 'Ansprechpartner Vertrieb:',
    'sales.form.company': 'Unternehmen',
    'sales.form.phone': 'Telefon',
    'sales.form.placeholder': 'Erzählen Sie uns von Ihrem Unternehmen und Ihrer Region...',
    'sales.service.support': 'Support',
    'sales.service.items': 'Wartung|Regelmäßige Inspektion und Wartung Ihrer Anlagen|Reparatur|Schnelle und zuverlässige Reparaturleistungen|Technische Beratung|Expertenwissen für Ihre Separationsprozesse|Inbetriebnahme|Professionelle Installation und Einweisung',

    // Integration Page
    'integration.planning.title': 'Integrationsplanung',
    'integration.planning.desc': 'Planung und Fertigung eines verbundenen Teilbereiches einer Anlage inklusive diverser Einzelkomponenten. Unsere Experten analysieren Ihre Prozesse und entwickeln maßgeschneiderte Lösungen.',
    'integration.planning.steps': 'Analyse Ihrer bestehenden Prozesse|Machbarkeitsstudie und Konzeptentwicklung|3D-Planung und Integration in Ihre Anlage|Schnittstellenklärung mit vorhandenen Systemen|Zeitplanung und Projektmanagement',
    'integration.installation.title': 'Installation & Inbetriebnahme',
    'integration.installation.desc': 'Unser erfahrenes Team führt die Installation und Inbetriebnahme durch und stellt sicher, dass alles optimal funktioniert.',
    'integration.installation.steps': 'Professionelle Montage vor Ort|Anschluss an vorhandene Systeme|Inbetriebnahme und Erstbefüllung|Schulung Ihrer Mitarbeiter|Dokumentation und Übergabe',
    'integration.cta.title': 'Bereit für die Integration?',
    'integration.cta.desc': 'Kontaktieren Sie uns für eine unverbindliche Beratung und ein individuelles Angebot.',
    'integration.cta.button': 'Kontakt aufnehmen',
    'integration.benefits.title': 'Ihre Vorteile',
    'integration.benefits.1.title': 'Maßgeschneiderte Lösungen',
    'integration.benefits.1.desc': 'Jede Integration wird individuell auf Ihre Anforderungen angepasst.',
    'integration.benefits.2.title': 'Erfahrene Experten',
    'integration.benefits.2.desc': 'Unser Team verfügt über jahrelange Erfahrung in der Anlagenintegration.',
    'integration.benefits.3.title': 'Effiziente Planung',
    'integration.benefits.3.desc': 'Minimale Stillstandszeiten durch professionelles Projektmanagement.',
    'integration.service.title': 'Unser Service',
    'integration.service.1.title': 'Weltweiter Service',
    'integration.service.1.desc': 'Installation und Inbetriebnahme weltweit durch unsere Partner.',
    'integration.service.2.title': 'Qualitätssicherung',
    'integration.service.2.desc': 'Umfassende Tests und Qualitätskontrollen vor der Übergabe.',
    'integration.service.3.title': 'Langfristige Betreuung',
    'integration.service.3.desc': 'Kontinuierlicher Support auch nach der Inbetriebnahme.',

    // Agriculture Page
    'agriculture.title': 'Landwirtschaft',
    'agriculture.subtitle': 'Effiziente Separationstechnologie für Gülle von Nutztieren und Gärreste aus Biogasanlagen.',
    'agriculture.intro.title': 'Maßgeschneiderte Lösungen für die',
    'agriculture.intro.highlight': 'Landwirtschaft',
    'agriculture.intro.desc': 'In der modernen Landwirtschaft ist der effiziente Umgang mit Nährstoffen und Abfallprodukten entscheidend für Produktivität und Nachhaltigkeit. Unsere EcoTech Filterschneckenpressen bieten bewährte, robuste und hochgradig effiziente Lösungen für die Trennung von festen und flüssigen Bestandteilen.',
    'agriculture.manure.title': 'Gülle von Nutztieren',
    'agriculture.manure.desc': 'Die Separation von Rinder- oder Schweinegülle reduziert das Lagervolumen der flüssigen Phase signifikant. Der gewonnene Feststoff eignet sich hervorragend als Dünger, während die flüssige Phase leichter auf die Felder ausgebracht werden kann.',
    'agriculture.manure.points': 'Volumenreduktion um bis zu 30%|Leichtere Ausbringung der dünnen Phase|Geruchsminderung|Feststoff als hochwertiger Kompost oder Einstreu nutzbar',
    'agriculture.biogas.title': 'Gärreste aus Biogasanlagen',
    'agriculture.biogas.desc': 'Biogasanlagen profitieren massiv von einer effizienten Separierung der Gärreste. Dies verbessert die Nährstofflogistik, verringert Transportkosten und optimiert den weiteren Betriebsablauf.',
    'agriculture.biogas.points': 'Optimierung der Nährstofflogistik|Reduzierung von Transport- und Lagerkosten|Homogenere flüssige Phase für besseres Handling|Verkaufsfähiger Festdünger',
    'agriculture.findProduct': 'Passendes Produkt finden',
    'agriculture.cta.title': 'Sind Sie bereit für die Separation der nächsten Generation?',
    'agriculture.cta.desc': 'Kontaktieren Sie uns für eine kostenlose technische Beratung und finden Sie heraus, wie unsere Filterschneckenpressen Ihren Betrieb optimieren können.',
    'agriculture.cta.button': 'Beratungstermin vereinbaren',

    // Applications Page
    'applications.findProduct': 'Passendes Produkt finden',
    'applications.page.subtitle': 'Entdecken Sie die vielfältigen Einsatzbereiche unserer Separationstechnologie – von der Landwirtschaft bis zur Lebensmittelindustrie.',
    'productpage.bg2.options': 'Automatische Wascheinrichtung für Filter- und Presssieb|Sensorpakete zur Überwachung|Steuerung ECO mit manueller Regelung|Steuerung PRO mit HMI-Panel und ProfiNET|Zulaufverrohrung mit Teleskoprohr|Steuerungsmodul für Zulaufpumpen|Zusätzlicher Fußrahmen für höhere Arbeitshöhe|Kundenspezifische Optionen nach Bedarf',
    'productpage.bgi400.features': 'Kompakte, günstige Maschine hauptsächlich für Agrar-Anwendungen|Hoher TS-Gehalt im Feststoff, geeignet zur Produktion von Einstreu|Einfache Plug&Play-Lösung mit angebautem Frequenzumrichter|Ausführung in Edelstahl (1.4301 / AISI 304)|Edelstahlschnecke mit Panzerung|Edelstahl-Spaltsiebe|Zulaufdruck bis 0,5 bar|Zulaufverrohrung mit Teleskoprohr und Überlaufrohr',
    'productpage.subtitle': 'Entdecken Sie unsere innovativen Separationslösungen für maximale Effizienz und Langlebigkeit.',

    // News Page
    'newspage.title': 'News & Medien',
    'newspage.downloads.title': 'Download',
    'newspage.downloads.desc': 'Bilder, Renderings, Prospekte',
    'newspage.downloads.text': 'Laden Sie unsere Produktbroschüren, technischen Datenblätter und Bilder herunter.',

    // Legal Pages
    'legal.terms.title': 'Allgemeine Geschäftsbedingungen',
    'legal.privacy.title': 'Datenschutzerklärung',
    'legal.imprint.title': 'Impressum',
    'legal.dealers.title': 'Unsere Händler',

    // Contact Form
    'form.name': 'Name',
    'form.email': 'E-Mail',
    'form.subject': 'Betreff',
    'form.message': 'Nachricht',
    'form.submit': 'Absenden',
    'form.sendApplication': 'Bewerbung senden',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.sales': 'Sales & Aftersales',
    'nav.applications': 'Applications',
    'nav.products': 'Products',
    'nav.integration': 'System Integration',
    'nav.news': 'News & Media',

    // Footer
    'footer.terms': 'Terms & Conditions',
    'footer.privacy': 'Privacy Policy',
    'footer.legal': 'Legal Notice',
    'footer.dealers': 'Dealers',

    // Hero
    'hero.headline': 'Next Level Separation',
    'hero.subheadline': 'Innovative Solid-Liquid Separation Solutions',
    'hero.cta': 'Learn More',

    // About Section
    'about.title': 'About Us',
    'about.description': 'With more than 15 years of experience in the development of technical applications in mechanical engineering and plant construction with a focus on separation and environmental technology.',
    'about.link': 'To Company Page',

    // Applications Section
    'applications.title': 'Applications',
    'applications.learnMore': 'Learn More',
    'applications.agriculture.title': 'Agriculture',
    'applications.agriculture.desc': 'Manure from livestock, fermentation residues from biogas plants',
    'applications.bedding.title': 'Green Bedding',
    'applications.bedding.desc': 'Separation for bedding and fertilizer production',
    'applications.biogas.title': 'Biogas',
    'applications.biogas.desc': 'Fermentation residues from biogas plants',
    'applications.recycling.title': 'Plastic Recycling',
    'applications.recycling.desc': 'Wastewater from depacking and plastic recycling plants',
    'applications.municipal.title': 'Municipal',
    'applications.municipal.desc': 'Primary and secondary sludge from sewage treatment plants',
    'applications.paper.title': 'Pulp & Paper',
    'applications.paper.desc': 'Rejects and secondary sludge',
    'applications.mdf.title': 'Process Media & Wastewater',
    'applications.mdf.desc': 'Production wastewater and process media from industrial plants',
    'applications.food.title': 'By-Products & Wastewater',
    'applications.food.desc': 'Slaughterhouse wastewater, washing water, brewery waste and industrial by-products',

    // Products Section
    'products.title': 'Products',
    'products.viewDetails': 'View Details',
    'products.bg2.name': 'Filter Press Screw BGII-800',
    'products.bg2.feature1': 'Up to 75m³/h throughput',
    'products.bg2.feature2': 'Up to 75% dry matter content',
    'products.bg2.feature3': 'Stainless steel construction',
    'products.bgi400.name': 'Filter Press Screw BGI-400',
    'products.bgi400.feature1': 'Up to 20m³/h throughput',
    'products.bgi400.feature2': 'Compact design',
    'products.bgi400.feature3': 'Plug & Play solution',

    // Why Separation Section
    'why.title': 'Why Separation?',
    'why.point1': 'Reduction of storage volume',
    'why.point2': 'Reuse of the solids',
    'why.point3': 'Reduction of disposal costs',
    'why.point4': 'Reuse of the effluent as process water',
    'why.point5': 'Reduction of energy costs',
    'why.point6': 'Reduction of process costs',
    'why.point7': 'Compliance with environmental regulations',
    'why.point8': 'Improved properties of the individual phases after separation',

    // Optimization Section
    'optimization.label': 'Process Optimization',
    'optimization.title': 'Measurably More Efficient',
    'optimization.text': 'We make separation processes measurably more efficient. Through intelligent optimizations, we reduce energy consumption, wear, and operating costs – while simultaneously increasing the performance of existing systems. It does not stop at the analysis: We implement improvements together with our customers consistently and create sustainable added value.',

    // News Section
    'news.title': 'News & Success Stories',
    'news.readMore': 'Read More',

    // About Page
    'aboutpage.intro.title': 'Who Are We?',
    'aboutpage.vision.title': 'Vision & Mission',
    'aboutpage.vision.label': 'Vision:',
    'aboutpage.vision.text': 'To bring separation technology to the next level',
    'aboutpage.slogan.label': 'Slogan:',
    'aboutpage.slogan.text': 'Next Level Separation',
    'aboutpage.mission.label': 'Mission:',
    'aboutpage.mission.text': 'We make separation processes measurably more efficient. Through intelligent optimizations, we reduce energy consumption, wear, and operating costs – while simultaneously increasing the performance of existing systems. It does not stop at the analysis: We implement improvements together with our customers consistently and create sustainable added value.',
    'aboutpage.team.title': 'Our Team',
    'aboutpage.team.ceo.name': 'Heinz Leitner',
    'aboutpage.team.ceo.role': 'CEO',
    'aboutpage.team.ceo.bio': '>15 years of management experience in international environmental technology machinery and plant construction',
    'aboutpage.team.coo.name': 'Gernot Pauger',
    'aboutpage.team.coo.role': 'COO',
    'aboutpage.team.coo.bio': '>15 years of experience in the development and production of special machines for environmental and agricultural technology',
    'aboutpage.team.cto.name': 'Thomas Kampl',
    'aboutpage.team.cto.role': 'CTO',
    'aboutpage.team.cto.bio': '>15 years of experience as an application specialist in separation technology for solid-liquid separation',
    'aboutpage.team.cso.name': 'Günther Pirker',
    'aboutpage.team.cso.role': 'CSO',
    'aboutpage.team.cso.bio': '>15 years of industry experience with focus on production and international sales of agricultural and environmental technology machinery',
    'aboutpage.team.description': 'We are an interdisciplinary team of engineers, application specialists and industry experts united by one goal: to develop technologically leading solutions for the separation of liquid and solid materials. Our approach is system-oriented and solution-focused. We holistically analyze established processing methods, develop customized machine and plant concepts with significantly higher efficiency, and rely on close cooperation with our customers.',

    // Partner Section
    'aboutpage.partner.title': 'Ecotech Styria - Partner',
    'aboutpage.partner.exclusive': 'exclusive Production Partner',
    'aboutpage.partner.ecotech.subtitle': 'Solid-Liquid Separation',
    'aboutpage.partner.ecotech.bullet1': 'R&D',
    'aboutpage.partner.ecotech.bullet2': 'Product Management',
    'aboutpage.partner.ecotech.bullet3': 'Sales',
    'aboutpage.partner.ecotech.bullet4': 'Customer Service',
    'aboutpage.partner.pauger.subtitle': 'Engineering & Production',
    'aboutpage.partner.pauger.bullet1': 'Engineering & Design',
    'aboutpage.partner.pauger.bullet2': 'Production of machines and components',
    'aboutpage.partner.pauger.bullet3': 'Spare parts warehouse',

    'aboutpage.contact.title': 'Contact',
    'aboutpage.location.title': 'Location',
    'aboutpage.careers.title': 'Careers – Open Positions',
    'aboutpage.careers.text': 'We are looking for talented and motivated professionals. Please send your application to: office@ecotechstyria.com',

    // Sales Page
    'sales.findPartner.title': 'Find a Sales Partner',
    'sales.findPartner.desc': 'Our sales partners are specialized in separation technology and provide local support and expertise.',
    'sales.becomePartner.title': 'Want to Become a Sales Partner?',
    'sales.spareparts.title': 'Spare Parts',
    'sales.spareparts.desc': 'We offer a comprehensive range of spare parts for all our machines. Contact us for a quote.',
    'sales.service.title': 'Service',
    'sales.service.desc': 'Our experienced service team is available for maintenance, repairs, and technical support.',

    // Products Page
    'productpage.bg2.title': 'Filter Press Screw BGII-800',
    'productpage.bg2.desc': 'The Filter Press Screw BGII-800 is our flagship machine for high-performance separations. With patented geometry and automatic washing device, it offers optimal efficiency and minimal wear.',

    // BG2 PDF Content
    'productpage.bg2.applications.ind.title': 'Industrial applications',
    'productpage.bg2.applications.ind.items': 'Plastic recycling|Pulp & Paper|Abattoir waste|Municipal waste water|Food industry',
    'productpage.bg2.applications.agr.title': 'Agricultural applications',
    'productpage.bg2.applications.agr.items': 'Manure from livestock|Digestates from biogas plants',
    'productpage.bg2.benefits.title': 'Benefits',
    'productpage.bg2.benefits.items': 'Reduction of disposal cost|Reuse of solids|Reuse of liquid fraction|Increased nutrient management|Increased process efficiency',
    'productpage.bg2.features.title': 'Key Features',
    'productpage.bg2.features.items': 'Stainless steel construction|Narrow gap between auger and screen|Up to 0.5 bar inlet pressure|Closed system, automatic washing device|Control units with open interface (ProfiNet etc.) for easy implementation|Low wear and increased throughput due to patented auger geometry and special screen basket housing in the pressing zone|Full Auto Control of the dry matter content in the solids|Monitoring of operation status (change in inlet consistency, leakages, torque, oil quality etc.)|Higly abrasion-resistant auger coating',
    'productpage.bg2.tech.title': 'Technical Data',
    'productpage.bg2.tech.drive': 'Drive power',
    'productpage.bg2.tech.drive.val': '5.5 - 11.0 kW',
    'productpage.bg2.tech.throughput': 'Throughput',
    'productpage.bg2.tech.throughput.val': 'up to 75m³/h',
    'productpage.bg2.tech.gap': 'Screen slot',
    'productpage.bg2.tech.gap.val': '100 - 1000 µm',
    'productpage.bg2.tech.dry_org': 'Dry matter organic fibers',
    'productpage.bg2.tech.dry_org.val': 'up to 40%',
    'productpage.bg2.tech.dry_inorg': 'Dry matter inorganic fibers',
    'productpage.bg2.tech.dry_inorg.val': 'up to 75%',
    'productpage.bg2.tech.disclaimer': 'Performance data depends on the consistency and viscosity of the medium to be separated.',
    'productpage.bgi400.title': 'Filter Press Screw BGI-400',
    'productpage.bgi400.desc': 'The compact Filter Press Screw BGI-400 is ideal for agricultural applications. With its plug-and-play solution and high dry matter content in solids, it offers a cost-effective solution for manure separation and bedding production.',
    'productpage.bgi400.availability': 'Available in Q4/25',

    // USP Section
    'productpage.usp.title': 'USP – Patented Technology',
    'productpage.usp.1.title': 'Patented Filter Screw Geometry',
    'productpage.usp.1.desc': 'The patented filter screw geometry with additional screw flights in the filter area provides increased specific throughput and reduced wear.',
    'productpage.usp.2.title': 'Patented Support Housing',
    'productpage.usp.2.desc': 'The patented support housing supports the press screen and absorbs burst pressure. Enables higher pressing pressure and thus higher dry matter content in the solids with reduced wear.',
    'productpage.usp.3.title': 'Automatic DM Control',
    'productpage.usp.3.desc': 'The automatic dry matter control reacts to changes in feed volume and consistency. Increases process reliability and enables constant operating conditions.',
    'productpage.usp.4.title': 'Fully Automatic Washing System',
    'productpage.usp.4.desc': '360° spray nozzles prevent buildup and blockages on the screen baskets. Operates in automatic intervals or by manual activation.',
    'productpage.voreindicker.title': 'Pre-Thickener',
    'productpage.voreindicker.desc': 'More information about our Pre-Thickener will follow shortly. Contact us for details.',
    'productpage.circulyizer.title': 'Circulyizer',
    'productpage.circulyizer.desc': 'More information about our Circulyizer will follow shortly. Contact us for details.',
    'productpage.inquiry': 'Send Inquiry',
    'productpage.new': 'New',
    'productpage.flagship': 'Flagship',
    'productpage.compact': 'Compact',
    'productpage.options': 'Options',
    'productpage.features': 'Features',
    'productpage.cta.title': 'Looking for Individual Consultation?',
    'productpage.cta.desc': 'Our sales team is available for personalized advice.',
    'productpage.cta.find': 'Find a Sales Partner',
    'productpage.cta.contact': 'Contact Us',

    // Ersatzteile Page
    'ersatzteile.hero.badge': 'Our Know-How is Your Strength',
    'ersatzteile.hero.title': 'Spare Parts in OEM Quality – for Maximum Machine Performance',
    'ersatzteile.hero.desc': 'Ecotech Styria spare parts stand for precision manufacturing, high durability and reliable availability. So your plant runs economically in the long term – with minimal operating costs and maximum process reliability.',
    'ersatzteile.hero.cta': 'Contact Us',
    'ersatzteile.hero.cta2': 'View Services',
    'ersatzteile.facts.title': 'Key Facts',
    'ersatzteile.facts.1.title': 'Precise & Reliable',
    'ersatzteile.facts.1.desc': 'Original parts to OE standard',
    'ersatzteile.facts.2.title': 'High Durability',
    'ersatzteile.facts.2.desc': 'Material & manufacturing for the application',
    'ersatzteile.facts.3.title': 'Fast Identification',
    'ersatzteile.facts.3.desc': 'Technical advice from spare parts experts',
    'ersatzteile.facts.4.title': 'Screw Reconditioning',
    'ersatzteile.facts.4.desc': 'Reconditioning & hard-facing for a "second life"',
    'ersatzteile.beratung.title': 'Expert Advice That Makes the Difference',
    'ersatzteile.beratung.desc': 'Our spare parts experts support you in identifying the right spare or wear part. With professional technical advice, we ensure you receive the right solution quickly and reliably.',
    'ersatzteile.beratung.1.title': 'Part Identification Support',
    'ersatzteile.beratung.1.desc': 'Reliable, fast and practical',
    'ersatzteile.beratung.2.title': 'Clear Specifications',
    'ersatzteile.beratung.2.desc': 'For smooth ordering & short downtimes',
    'ersatzteile.preis.badge': 'Your Benefits',
    'ersatzteile.preis.title': 'Best Price-Performance Ratio',
    'ersatzteile.preis.desc': 'The efficiency of your plant is largely determined by the quality of the spare parts used. Whether screen basket or press screw – original Ecotech Styria spare parts deliver sustainable advantages in operation.',
    'ersatzteile.preis.1.title': 'Longer Service Life',
    'ersatzteile.preis.1.desc': 'Significantly higher durability compared to aftermarket parts',
    'ersatzteile.preis.2.title': 'Less Maintenance',
    'ersatzteile.preis.2.desc': 'Reduced downtime and lower maintenance costs',
    'ersatzteile.preis.3.title': 'Higher Machine Availability',
    'ersatzteile.preis.3.desc': 'Maximum performance at minimal operating costs',
    'ersatzteile.schnecken.badge': 'Service',
    'ersatzteile.schnecken.title': 'Screw Reconditioning – Quality at the Core of the Separator',
    'ersatzteile.schnecken.desc1': 'Screws are the central functional elements in separators – their quality is crucial for performance, service life and economic efficiency of the entire machine. Precisely maintained tolerances, process-reliable geometry and professional hard-facing with suitable methods and materials are essential for maximum wear resistance.',
    'ersatzteile.schnecken.desc2': 'Ecotech Styria offers professional reconditioning of your press screw. Through targeted repair, geometry adjustment and renewed wear coating, we give your screw a second life – economically, sustainably and in proven Ecotech Styria quality.',
    'ersatzteile.schnecken.1': 'Precise Tolerances — For stable processes and reproducible performance',
    'ersatzteile.schnecken.2': 'Hard-facing with Suitable Methods — Material & method for high wear resistance',
    'ersatzteile.schnecken.3': '"Second Life" for Your Press Screw — Professional reconditioning instead of costly replacement',
    'ersatzteile.oem.title': 'OEM Quality Over the Entire Machine Lifetime',
    'ersatzteile.oem.desc': 'Our spare and wear parts are developed and manufactured together with the original equipment. They are 100% precisely fitting, operationally safe and meet the same high quality standards as the original equipment.',
    'ersatzteile.tech.title': 'Always State of the Art',
    'ersatzteile.tech.desc': 'The continuous development of our products is part of our identity. This know-how naturally flows into our spare and wear parts – for future-proof solutions and consistently high plant performance.',
    'ersatzteile.contact.title': 'Quick to the Right Part – with Our Service',
    'ersatzteile.contact.desc': 'Send us your machine or part information – we support you with identification and create a suitable offer. Including screw reconditioning on request.',
    'ersatzteile.contact.cta': 'Send Email',
    'ersatzteile.contact.box.title': 'Your Contact for Spare Parts',

    // Service Page
    'service.hero.badge': 'On-Site Service · Plannable · Fast',
    'service.hero.title': 'Professional Maintenance with Ecotech Styria',
    'service.hero.desc': 'Regular maintenance reduces unplanned downtimes, preserves machine value and prevents consequential damage. Our service technicians support you efficiently and practically – directly at your site.',
    'service.hero.cta': 'Contact Service',
    'service.facts.title': 'Key Facts',
    'service.facts.1': 'On-site service with modern equipped service vehicles',
    'service.facts.2': 'Experienced and trained service technicians',
    'service.facts.3': 'Maintenance & servicing – plannable and documented',
    'service.facts.4': 'Option: turnkey installation & commissioning',
    'service.regular.title': 'Regular Service – Less Downtime, More Reliability',
    'service.regular.desc': 'Regularly maintained machines operate more stably, efficiently and cause fewer unplanned failures. At the same time, machine value is preserved long-term.',
    'service.regular.1': 'Minimize unplanned downtimes',
    'service.regular.2': 'Preserve machine value long-term',
    'service.regular.3': 'Reduce internal maintenance effort',
    'service.regular.4': 'Ensure calculable, transparent service costs',
    'service.install.title': 'Turnkey Installation & Commissioning',
    'service.install.desc': 'On request, we handle installation and commissioning of your new machine or plant – including training for efficient and safe operation.',
    'service.install.1': 'Professional assembly and clean integration into the process',
    'service.install.2': 'Commissioning & functional testing to defined standards',
    'service.install.3': 'Training of operating personnel for safe, efficient operation',
    'service.install.cta': 'Inquire Now',

    // Sales Page
    'sales.partner.label': 'Partnership',
    'sales.partner.desc': 'Haven\'t found a suitable sales partner? Become part of our global distribution network and benefit from our expertise in separation technology.',
    'sales.partner.tcs': 'See',
    'sales.partner.tcs.link': 'Partners of TCS Umwelttechnik',
    'sales.partner.find': 'Find a Sales Partner',
    'sales.partner.notfound': 'Haven\'t found a suitable sales partner',
    'sales.partner.become': 'Want to become a sales partner',
    'sales.partner.contact': 'Sales Contact:',
    'sales.form.company': 'Company',
    'sales.form.phone': 'Phone',
    'sales.form.placeholder': 'Tell us about your company and your region...',
    'sales.service.support': 'Support',
    'sales.service.items': 'Maintenance|Regular inspection and maintenance of your systems|Repair|Fast and reliable repair services|Technical Consulting|Expert knowledge for your separation processes|Commissioning|Professional installation and training',

    // Integration Page
    'integration.planning.title': 'Integration Planning',
    'integration.planning.desc': 'We plan the integration of our machines into your existing systems. Our experts analyze your processes and develop customized solutions.',
    'integration.planning.steps': 'Analysis of your existing processes|Feasibility study and concept development|3D planning and integration into your plant|Interface clarification with existing systems|Scheduling and project management',
    'integration.installation.title': 'Installation & Commissioning',
    'integration.installation.desc': 'Our experienced team handles installation and commissioning, ensuring everything works optimally.',
    'integration.installation.steps': 'Professional on-site assembly|Connection to existing systems|Commissioning and initial filling|Training of your staff|Documentation and handover',
    'integration.cta.title': 'Ready for Integration?',
    'integration.cta.desc': 'Contact us for a non-binding consultation and an individual offer.',
    'integration.cta.button': 'Contact Us',
    'integration.benefits.title': 'Your Benefits',
    'integration.benefits.1.title': 'Customized Solutions',
    'integration.benefits.1.desc': 'Every integration is individually tailored to your requirements.',
    'integration.benefits.2.title': 'Experienced Experts',
    'integration.benefits.2.desc': 'Our team has years of experience in plant integration.',
    'integration.benefits.3.title': 'Efficient Planning',
    'integration.benefits.3.desc': 'Minimal downtime through professional project management.',
    'integration.service.title': 'Our Service',
    'integration.service.1.title': 'Worldwide Service',
    'integration.service.1.desc': 'Installation and commissioning worldwide through our partners.',
    'integration.service.2.title': 'Quality Assurance',
    'integration.service.2.desc': 'Comprehensive testing and quality controls before handover.',
    'integration.service.3.title': 'Long-term Support',
    'integration.service.3.desc': 'Continuous support even after commissioning.',

    // Agriculture Page
    'agriculture.title': 'Agriculture',
    'agriculture.subtitle': 'Efficient separation technology for livestock manure and fermentation residues from biogas plants.',
    'agriculture.intro.title': 'Customized Solutions for',
    'agriculture.intro.highlight': 'Agriculture',
    'agriculture.intro.desc': 'In modern agriculture, efficient management of nutrients and waste products is crucial for productivity and sustainability. Our EcoTech filter screw presses offer proven, robust and highly efficient solutions for separating solid and liquid components.',
    'agriculture.manure.title': 'Livestock Manure',
    'agriculture.manure.desc': 'The separation of cattle or pig manure significantly reduces the storage volume of the liquid phase. The recovered solid is excellent as fertilizer, while the liquid phase can be more easily applied to fields.',
    'agriculture.manure.points': 'Volume reduction of up to 30%|Easier application of the thin phase|Odor reduction|Solids usable as high-quality compost or bedding',
    'agriculture.biogas.title': 'Fermentation Residues from Biogas Plants',
    'agriculture.biogas.desc': 'Biogas plants benefit enormously from efficient separation of digestate. This improves nutrient logistics, reduces transport costs and optimizes operations.',
    'agriculture.biogas.points': 'Optimization of nutrient logistics|Reduction of transport and storage costs|More homogeneous liquid phase for better handling|Marketable solid fertilizer',
    'agriculture.findProduct': 'Find the Right Product',
    'agriculture.cta.title': 'Ready for Next-Generation Separation?',
    'agriculture.cta.desc': 'Contact us for a free technical consultation and find out how our filter screw presses can optimize your operations.',
    'agriculture.cta.button': 'Schedule a Consultation',

    // Applications Page
    'applications.findProduct': 'Find the Right Product',
    'applications.page.subtitle': 'Discover the diverse applications of our separation technology – from agriculture to the food industry.',
    'productpage.bg2.options': 'Automatic washing device for filter and press screen|Sensor packages for monitoring|ECO control with manual regulation|PRO control with HMI panel and ProfiNET|Inlet piping with telescopic pipe|Control module for feed pumps|Additional base frame for higher working height|Customer-specific options as needed',
    'productpage.bgi400.features': 'Compact, cost-effective machine mainly for agricultural applications|High DM content in solids, suitable for bedding production|Simple plug & play solution with built-in frequency converter|Stainless steel design (1.4301 / AISI 304)|Stainless steel screw with hard-facing|Stainless steel slot screens|Inlet pressure up to 0.5 bar|Inlet piping with telescopic pipe and overflow pipe',
    'productpage.subtitle': 'Discover our innovative separation solutions for maximum efficiency and longevity.',

    // News Page
    'newspage.title': 'News & Media',
    'newspage.downloads.title': 'Downloads',
    'newspage.downloads.desc': 'Images, Renderings, Brochures',
    'newspage.downloads.text': 'Download our product brochures, technical data sheets, and images.',

    // Legal Pages
    'legal.terms.title': 'Terms & Conditions',
    'legal.privacy.title': 'Privacy Policy',
    'legal.imprint.title': 'Legal Notice',
    'legal.dealers.title': 'Our Dealers',

    // Contact Form
    'form.name': 'Name',
    'form.email': 'Email',
    'form.subject': 'Subject',
    'form.message': 'Message',
    'form.submit': 'Submit',
    'form.sendApplication': 'Send Application',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('de');

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    document.documentElement.lang = lang;
  }, []);

  const t = useCallback((key: string): string => {
    const translation = translations[language][key as keyof typeof translations.de];
    return translation || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
